// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: playtesthub/v1/permission.proto

package playtesthubv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_CREATE      Action = 1
	Action_ACTION_READ        Action = 2
	Action_ACTION_UPDATE      Action = 4
	Action_ACTION_DELETE      Action = 8
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_CREATE",
		2: "ACTION_READ",
		4: "ACTION_UPDATE",
		8: "ACTION_DELETE",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_CREATE":      1,
		"ACTION_READ":        2,
		"ACTION_UPDATE":      4,
		"ACTION_DELETE":      8,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_playtesthub_v1_permission_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_playtesthub_v1_permission_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_playtesthub_v1_permission_proto_rawDescGZIP(), []int{0}
}

var file_playtesthub_v1_permission_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "playtesthub.v1.resource",
		Tag:           "bytes,50001,opt,name=resource",
		Filename:      "playtesthub/v1/permission.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Action)(nil),
		Field:         50002,
		Name:          "playtesthub.v1.action",
		Tag:           "varint,50002,opt,name=action,enum=playtesthub.v1.Action",
		Filename:      "playtesthub/v1/permission.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string resource = 50001;
	E_Resource = &file_playtesthub_v1_permission_proto_extTypes[0]
	// optional playtesthub.v1.Action action = 50002;
	E_Action = &file_playtesthub_v1_permission_proto_extTypes[1]
)

var File_playtesthub_v1_permission_proto protoreflect.FileDescriptor

const file_playtesthub_v1_permission_proto_rawDesc = "" +
	"\n" +
	"\x1fplaytesthub/v1/permission.proto\x12\x0eplaytesthub.v1\x1a google/protobuf/descriptor.proto*j\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACTION_CREATE\x10\x01\x12\x0f\n" +
	"\vACTION_READ\x10\x02\x12\x11\n" +
	"\rACTION_UPDATE\x10\x04\x12\x11\n" +
	"\rACTION_DELETE\x10\b:<\n" +
	"\bresource\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\tR\bresource:P\n" +
	"\x06action\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\x0e2\x16.playtesthub.v1.ActionR\x06actionBKZIgithub.com/anggorodewanto/playtesthub/pkg/pb/playtesthub/v1;playtesthubv1b\x06proto3"

var (
	file_playtesthub_v1_permission_proto_rawDescOnce sync.Once
	file_playtesthub_v1_permission_proto_rawDescData []byte
)

func file_playtesthub_v1_permission_proto_rawDescGZIP() []byte {
	file_playtesthub_v1_permission_proto_rawDescOnce.Do(func() {
		file_playtesthub_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_playtesthub_v1_permission_proto_rawDesc), len(file_playtesthub_v1_permission_proto_rawDesc)))
	})
	return file_playtesthub_v1_permission_proto_rawDescData
}

var file_playtesthub_v1_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_playtesthub_v1_permission_proto_goTypes = []any{
	(Action)(0),                        // 0: playtesthub.v1.Action
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_playtesthub_v1_permission_proto_depIdxs = []int32{
	1, // 0: playtesthub.v1.resource:extendee -> google.protobuf.MethodOptions
	1, // 1: playtesthub.v1.action:extendee -> google.protobuf.MethodOptions
	0, // 2: playtesthub.v1.action:type_name -> playtesthub.v1.Action
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_playtesthub_v1_permission_proto_init() }
func file_playtesthub_v1_permission_proto_init() {
	if File_playtesthub_v1_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_playtesthub_v1_permission_proto_rawDesc), len(file_playtesthub_v1_permission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_playtesthub_v1_permission_proto_goTypes,
		DependencyIndexes: file_playtesthub_v1_permission_proto_depIdxs,
		EnumInfos:         file_playtesthub_v1_permission_proto_enumTypes,
		ExtensionInfos:    file_playtesthub_v1_permission_proto_extTypes,
	}.Build()
	File_playtesthub_v1_permission_proto = out.File
	file_playtesthub_v1_permission_proto_goTypes = nil
	file_playtesthub_v1_permission_proto_depIdxs = nil
}
