// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: playtesthub/v1/playtesthub.proto

package playtesthubv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Platform int32

const (
	Platform_PLATFORM_UNSPECIFIED Platform = 0
	Platform_PLATFORM_STEAM       Platform = 1
	Platform_PLATFORM_XBOX        Platform = 2
	Platform_PLATFORM_PLAYSTATION Platform = 3
	Platform_PLATFORM_EPIC        Platform = 4
	Platform_PLATFORM_OTHER       Platform = 5
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "PLATFORM_STEAM",
		2: "PLATFORM_XBOX",
		3: "PLATFORM_PLAYSTATION",
		4: "PLATFORM_EPIC",
		5: "PLATFORM_OTHER",
	}
	Platform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED": 0,
		"PLATFORM_STEAM":       1,
		"PLATFORM_XBOX":        2,
		"PLATFORM_PLAYSTATION": 3,
		"PLATFORM_EPIC":        4,
		"PLATFORM_OTHER":       5,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_playtesthub_v1_playtesthub_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_playtesthub_v1_playtesthub_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{0}
}

type PlaytestStatus int32

const (
	PlaytestStatus_PLAYTEST_STATUS_UNSPECIFIED PlaytestStatus = 0
	PlaytestStatus_PLAYTEST_STATUS_DRAFT       PlaytestStatus = 1
	PlaytestStatus_PLAYTEST_STATUS_OPEN        PlaytestStatus = 2
	PlaytestStatus_PLAYTEST_STATUS_CLOSED      PlaytestStatus = 3
)

// Enum value maps for PlaytestStatus.
var (
	PlaytestStatus_name = map[int32]string{
		0: "PLAYTEST_STATUS_UNSPECIFIED",
		1: "PLAYTEST_STATUS_DRAFT",
		2: "PLAYTEST_STATUS_OPEN",
		3: "PLAYTEST_STATUS_CLOSED",
	}
	PlaytestStatus_value = map[string]int32{
		"PLAYTEST_STATUS_UNSPECIFIED": 0,
		"PLAYTEST_STATUS_DRAFT":       1,
		"PLAYTEST_STATUS_OPEN":        2,
		"PLAYTEST_STATUS_CLOSED":      3,
	}
)

func (x PlaytestStatus) Enum() *PlaytestStatus {
	p := new(PlaytestStatus)
	*p = x
	return p
}

func (x PlaytestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlaytestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_playtesthub_v1_playtesthub_proto_enumTypes[1].Descriptor()
}

func (PlaytestStatus) Type() protoreflect.EnumType {
	return &file_playtesthub_v1_playtesthub_proto_enumTypes[1]
}

func (x PlaytestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlaytestStatus.Descriptor instead.
func (PlaytestStatus) EnumDescriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{1}
}

type DistributionModel int32

const (
	DistributionModel_DISTRIBUTION_MODEL_UNSPECIFIED  DistributionModel = 0
	DistributionModel_DISTRIBUTION_MODEL_STEAM_KEYS   DistributionModel = 1
	DistributionModel_DISTRIBUTION_MODEL_AGS_CAMPAIGN DistributionModel = 2
)

// Enum value maps for DistributionModel.
var (
	DistributionModel_name = map[int32]string{
		0: "DISTRIBUTION_MODEL_UNSPECIFIED",
		1: "DISTRIBUTION_MODEL_STEAM_KEYS",
		2: "DISTRIBUTION_MODEL_AGS_CAMPAIGN",
	}
	DistributionModel_value = map[string]int32{
		"DISTRIBUTION_MODEL_UNSPECIFIED":  0,
		"DISTRIBUTION_MODEL_STEAM_KEYS":   1,
		"DISTRIBUTION_MODEL_AGS_CAMPAIGN": 2,
	}
)

func (x DistributionModel) Enum() *DistributionModel {
	p := new(DistributionModel)
	*p = x
	return p
}

func (x DistributionModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistributionModel) Descriptor() protoreflect.EnumDescriptor {
	return file_playtesthub_v1_playtesthub_proto_enumTypes[2].Descriptor()
}

func (DistributionModel) Type() protoreflect.EnumType {
	return &file_playtesthub_v1_playtesthub_proto_enumTypes[2]
}

func (x DistributionModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistributionModel.Descriptor instead.
func (DistributionModel) EnumDescriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{2}
}

type ApplicantStatus int32

const (
	ApplicantStatus_APPLICANT_STATUS_UNSPECIFIED ApplicantStatus = 0
	ApplicantStatus_APPLICANT_STATUS_PENDING     ApplicantStatus = 1
	ApplicantStatus_APPLICANT_STATUS_APPROVED    ApplicantStatus = 2
	ApplicantStatus_APPLICANT_STATUS_REJECTED    ApplicantStatus = 3
)

// Enum value maps for ApplicantStatus.
var (
	ApplicantStatus_name = map[int32]string{
		0: "APPLICANT_STATUS_UNSPECIFIED",
		1: "APPLICANT_STATUS_PENDING",
		2: "APPLICANT_STATUS_APPROVED",
		3: "APPLICANT_STATUS_REJECTED",
	}
	ApplicantStatus_value = map[string]int32{
		"APPLICANT_STATUS_UNSPECIFIED": 0,
		"APPLICANT_STATUS_PENDING":     1,
		"APPLICANT_STATUS_APPROVED":    2,
		"APPLICANT_STATUS_REJECTED":    3,
	}
)

func (x ApplicantStatus) Enum() *ApplicantStatus {
	p := new(ApplicantStatus)
	*p = x
	return p
}

func (x ApplicantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_playtesthub_v1_playtesthub_proto_enumTypes[3].Descriptor()
}

func (ApplicantStatus) Type() protoreflect.EnumType {
	return &file_playtesthub_v1_playtesthub_proto_enumTypes[3]
}

func (x ApplicantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicantStatus.Descriptor instead.
func (ApplicantStatus) EnumDescriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{3}
}

type DmStatus int32

const (
	DmStatus_DM_STATUS_UNSPECIFIED DmStatus = 0
	DmStatus_DM_STATUS_SENT        DmStatus = 1
	DmStatus_DM_STATUS_FAILED      DmStatus = 2
)

// Enum value maps for DmStatus.
var (
	DmStatus_name = map[int32]string{
		0: "DM_STATUS_UNSPECIFIED",
		1: "DM_STATUS_SENT",
		2: "DM_STATUS_FAILED",
	}
	DmStatus_value = map[string]int32{
		"DM_STATUS_UNSPECIFIED": 0,
		"DM_STATUS_SENT":        1,
		"DM_STATUS_FAILED":      2,
	}
)

func (x DmStatus) Enum() *DmStatus {
	p := new(DmStatus)
	*p = x
	return p
}

func (x DmStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DmStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_playtesthub_v1_playtesthub_proto_enumTypes[4].Descriptor()
}

func (DmStatus) Type() protoreflect.EnumType {
	return &file_playtesthub_v1_playtesthub_proto_enumTypes[4]
}

func (x DmStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DmStatus.Descriptor instead.
func (DmStatus) EnumDescriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{4}
}

// Playtest is the full admin-visible entity. Field semantics: PRD §5.1.
type Playtest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace             string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Slug                  string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Title                 string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description           string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	BannerImageUrl        string                 `protobuf:"bytes,6,opt,name=banner_image_url,json=bannerImageUrl,proto3" json:"banner_image_url,omitempty"`
	Platforms             []Platform             `protobuf:"varint,7,rep,packed,name=platforms,proto3,enum=playtesthub.v1.Platform" json:"platforms,omitempty"`
	StartsAt              *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt                *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Status                PlaytestStatus         `protobuf:"varint,10,opt,name=status,proto3,enum=playtesthub.v1.PlaytestStatus" json:"status,omitempty"`
	NdaRequired           bool                   `protobuf:"varint,11,opt,name=nda_required,json=ndaRequired,proto3" json:"nda_required,omitempty"`
	NdaText               string                 `protobuf:"bytes,12,opt,name=nda_text,json=ndaText,proto3" json:"nda_text,omitempty"`
	CurrentNdaVersionHash string                 `protobuf:"bytes,13,opt,name=current_nda_version_hash,json=currentNdaVersionHash,proto3" json:"current_nda_version_hash,omitempty"`
	SurveyId              *string                `protobuf:"bytes,14,opt,name=survey_id,json=surveyId,proto3,oneof" json:"survey_id,omitempty"`
	DistributionModel     DistributionModel      `protobuf:"varint,15,opt,name=distribution_model,json=distributionModel,proto3,enum=playtesthub.v1.DistributionModel" json:"distribution_model,omitempty"`
	AgsItemId             *string                `protobuf:"bytes,16,opt,name=ags_item_id,json=agsItemId,proto3,oneof" json:"ags_item_id,omitempty"`
	AgsCampaignId         *string                `protobuf:"bytes,17,opt,name=ags_campaign_id,json=agsCampaignId,proto3,oneof" json:"ags_campaign_id,omitempty"`
	InitialCodeQuantity   *int32                 `protobuf:"varint,18,opt,name=initial_code_quantity,json=initialCodeQuantity,proto3,oneof" json:"initial_code_quantity,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt             *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Playtest) Reset() {
	*x = Playtest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playtest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playtest) ProtoMessage() {}

func (x *Playtest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playtest.ProtoReflect.Descriptor instead.
func (*Playtest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{0}
}

func (x *Playtest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Playtest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Playtest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Playtest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Playtest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Playtest) GetBannerImageUrl() string {
	if x != nil {
		return x.BannerImageUrl
	}
	return ""
}

func (x *Playtest) GetPlatforms() []Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *Playtest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *Playtest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *Playtest) GetStatus() PlaytestStatus {
	if x != nil {
		return x.Status
	}
	return PlaytestStatus_PLAYTEST_STATUS_UNSPECIFIED
}

func (x *Playtest) GetNdaRequired() bool {
	if x != nil {
		return x.NdaRequired
	}
	return false
}

func (x *Playtest) GetNdaText() string {
	if x != nil {
		return x.NdaText
	}
	return ""
}

func (x *Playtest) GetCurrentNdaVersionHash() string {
	if x != nil {
		return x.CurrentNdaVersionHash
	}
	return ""
}

func (x *Playtest) GetSurveyId() string {
	if x != nil && x.SurveyId != nil {
		return *x.SurveyId
	}
	return ""
}

func (x *Playtest) GetDistributionModel() DistributionModel {
	if x != nil {
		return x.DistributionModel
	}
	return DistributionModel_DISTRIBUTION_MODEL_UNSPECIFIED
}

func (x *Playtest) GetAgsItemId() string {
	if x != nil && x.AgsItemId != nil {
		return *x.AgsItemId
	}
	return ""
}

func (x *Playtest) GetAgsCampaignId() string {
	if x != nil && x.AgsCampaignId != nil {
		return *x.AgsCampaignId
	}
	return ""
}

func (x *Playtest) GetInitialCodeQuantity() int32 {
	if x != nil && x.InitialCodeQuantity != nil {
		return *x.InitialCodeQuantity
	}
	return 0
}

func (x *Playtest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Playtest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Playtest) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// PublicPlaytest is the restricted field set exposed to unauthenticated
// callers on GetPublicPlaytest (PRD §5.2).
type PublicPlaytest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Slug           string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	BannerImageUrl string                 `protobuf:"bytes,4,opt,name=banner_image_url,json=bannerImageUrl,proto3" json:"banner_image_url,omitempty"`
	Platforms      []Platform             `protobuf:"varint,5,rep,packed,name=platforms,proto3,enum=playtesthub.v1.Platform" json:"platforms,omitempty"`
	StartsAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublicPlaytest) Reset() {
	*x = PublicPlaytest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicPlaytest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicPlaytest) ProtoMessage() {}

func (x *PublicPlaytest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicPlaytest.ProtoReflect.Descriptor instead.
func (*PublicPlaytest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{1}
}

func (x *PublicPlaytest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PublicPlaytest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublicPlaytest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublicPlaytest) GetBannerImageUrl() string {
	if x != nil {
		return x.BannerImageUrl
	}
	return ""
}

func (x *PublicPlaytest) GetPlatforms() []Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *PublicPlaytest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *PublicPlaytest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

// PlayerPlaytest is the field set returned to authenticated player callers
// (GetPlaytestForPlayer). Superset of PublicPlaytest plus NDA + distribution
// + status fields needed for the player flow.
type PlayerPlaytest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Slug                  string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title                 string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description           string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	BannerImageUrl        string                 `protobuf:"bytes,4,opt,name=banner_image_url,json=bannerImageUrl,proto3" json:"banner_image_url,omitempty"`
	Platforms             []Platform             `protobuf:"varint,5,rep,packed,name=platforms,proto3,enum=playtesthub.v1.Platform" json:"platforms,omitempty"`
	StartsAt              *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt                *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Status                PlaytestStatus         `protobuf:"varint,8,opt,name=status,proto3,enum=playtesthub.v1.PlaytestStatus" json:"status,omitempty"`
	NdaRequired           bool                   `protobuf:"varint,9,opt,name=nda_required,json=ndaRequired,proto3" json:"nda_required,omitempty"`
	NdaText               string                 `protobuf:"bytes,10,opt,name=nda_text,json=ndaText,proto3" json:"nda_text,omitempty"`
	CurrentNdaVersionHash string                 `protobuf:"bytes,11,opt,name=current_nda_version_hash,json=currentNdaVersionHash,proto3" json:"current_nda_version_hash,omitempty"`
	SurveyId              *string                `protobuf:"bytes,12,opt,name=survey_id,json=surveyId,proto3,oneof" json:"survey_id,omitempty"`
	DistributionModel     DistributionModel      `protobuf:"varint,13,opt,name=distribution_model,json=distributionModel,proto3,enum=playtesthub.v1.DistributionModel" json:"distribution_model,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlayerPlaytest) Reset() {
	*x = PlayerPlaytest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPlaytest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPlaytest) ProtoMessage() {}

func (x *PlayerPlaytest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPlaytest.ProtoReflect.Descriptor instead.
func (*PlayerPlaytest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerPlaytest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PlayerPlaytest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PlayerPlaytest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlayerPlaytest) GetBannerImageUrl() string {
	if x != nil {
		return x.BannerImageUrl
	}
	return ""
}

func (x *PlayerPlaytest) GetPlatforms() []Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *PlayerPlaytest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *PlayerPlaytest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *PlayerPlaytest) GetStatus() PlaytestStatus {
	if x != nil {
		return x.Status
	}
	return PlaytestStatus_PLAYTEST_STATUS_UNSPECIFIED
}

func (x *PlayerPlaytest) GetNdaRequired() bool {
	if x != nil {
		return x.NdaRequired
	}
	return false
}

func (x *PlayerPlaytest) GetNdaText() string {
	if x != nil {
		return x.NdaText
	}
	return ""
}

func (x *PlayerPlaytest) GetCurrentNdaVersionHash() string {
	if x != nil {
		return x.CurrentNdaVersionHash
	}
	return ""
}

func (x *PlayerPlaytest) GetSurveyId() string {
	if x != nil && x.SurveyId != nil {
		return *x.SurveyId
	}
	return ""
}

func (x *PlayerPlaytest) GetDistributionModel() DistributionModel {
	if x != nil {
		return x.DistributionModel
	}
	return DistributionModel_DISTRIBUTION_MODEL_UNSPECIFIED
}

// Applicant is the full admin-visible entity (schema.md §"Applicant entity").
// Player-visible responses carry the same message with restricted fields
// populated — the handler layer enforces the visibility split (schema.md
// L86–88). Player-visible: status, granted_code_id (presence), approved_at,
// nda_version_hash.
type Applicant struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlaytestId      string                 `protobuf:"bytes,2,opt,name=playtest_id,json=playtestId,proto3" json:"playtest_id,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DiscordHandle   string                 `protobuf:"bytes,4,opt,name=discord_handle,json=discordHandle,proto3" json:"discord_handle,omitempty"`
	Platforms       []Platform             `protobuf:"varint,5,rep,packed,name=platforms,proto3,enum=playtesthub.v1.Platform" json:"platforms,omitempty"`
	NdaVersionHash  *string                `protobuf:"bytes,6,opt,name=nda_version_hash,json=ndaVersionHash,proto3,oneof" json:"nda_version_hash,omitempty"`
	Status          ApplicantStatus        `protobuf:"varint,7,opt,name=status,proto3,enum=playtesthub.v1.ApplicantStatus" json:"status,omitempty"`
	GrantedCodeId   *string                `protobuf:"bytes,8,opt,name=granted_code_id,json=grantedCodeId,proto3,oneof" json:"granted_code_id,omitempty"`
	ApprovedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	RejectionReason *string                `protobuf:"bytes,10,opt,name=rejection_reason,json=rejectionReason,proto3,oneof" json:"rejection_reason,omitempty"`
	LastDmStatus    DmStatus               `protobuf:"varint,11,opt,name=last_dm_status,json=lastDmStatus,proto3,enum=playtesthub.v1.DmStatus" json:"last_dm_status,omitempty"`
	LastDmAttemptAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_dm_attempt_at,json=lastDmAttemptAt,proto3" json:"last_dm_attempt_at,omitempty"`
	LastDmError     *string                `protobuf:"bytes,13,opt,name=last_dm_error,json=lastDmError,proto3,oneof" json:"last_dm_error,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Applicant) Reset() {
	*x = Applicant{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Applicant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Applicant) ProtoMessage() {}

func (x *Applicant) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Applicant.ProtoReflect.Descriptor instead.
func (*Applicant) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{3}
}

func (x *Applicant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Applicant) GetPlaytestId() string {
	if x != nil {
		return x.PlaytestId
	}
	return ""
}

func (x *Applicant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Applicant) GetDiscordHandle() string {
	if x != nil {
		return x.DiscordHandle
	}
	return ""
}

func (x *Applicant) GetPlatforms() []Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *Applicant) GetNdaVersionHash() string {
	if x != nil && x.NdaVersionHash != nil {
		return *x.NdaVersionHash
	}
	return ""
}

func (x *Applicant) GetStatus() ApplicantStatus {
	if x != nil {
		return x.Status
	}
	return ApplicantStatus_APPLICANT_STATUS_UNSPECIFIED
}

func (x *Applicant) GetGrantedCodeId() string {
	if x != nil && x.GrantedCodeId != nil {
		return *x.GrantedCodeId
	}
	return ""
}

func (x *Applicant) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *Applicant) GetRejectionReason() string {
	if x != nil && x.RejectionReason != nil {
		return *x.RejectionReason
	}
	return ""
}

func (x *Applicant) GetLastDmStatus() DmStatus {
	if x != nil {
		return x.LastDmStatus
	}
	return DmStatus_DM_STATUS_UNSPECIFIED
}

func (x *Applicant) GetLastDmAttemptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastDmAttemptAt
	}
	return nil
}

func (x *Applicant) GetLastDmError() string {
	if x != nil && x.LastDmError != nil {
		return *x.LastDmError
	}
	return ""
}

func (x *Applicant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetPublicPlaytestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicPlaytestRequest) Reset() {
	*x = GetPublicPlaytestRequest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicPlaytestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicPlaytestRequest) ProtoMessage() {}

func (x *GetPublicPlaytestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicPlaytestRequest.ProtoReflect.Descriptor instead.
func (*GetPublicPlaytestRequest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{4}
}

func (x *GetPublicPlaytestRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetPublicPlaytestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playtest      *PublicPlaytest        `protobuf:"bytes,1,opt,name=playtest,proto3" json:"playtest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicPlaytestResponse) Reset() {
	*x = GetPublicPlaytestResponse{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicPlaytestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicPlaytestResponse) ProtoMessage() {}

func (x *GetPublicPlaytestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicPlaytestResponse.ProtoReflect.Descriptor instead.
func (*GetPublicPlaytestResponse) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{5}
}

func (x *GetPublicPlaytestResponse) GetPlaytest() *PublicPlaytest {
	if x != nil {
		return x.Playtest
	}
	return nil
}

type GetPlaytestForPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaytestForPlayerRequest) Reset() {
	*x = GetPlaytestForPlayerRequest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaytestForPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaytestForPlayerRequest) ProtoMessage() {}

func (x *GetPlaytestForPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaytestForPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlaytestForPlayerRequest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlaytestForPlayerRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetPlaytestForPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playtest      *PlayerPlaytest        `protobuf:"bytes,1,opt,name=playtest,proto3" json:"playtest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaytestForPlayerResponse) Reset() {
	*x = GetPlaytestForPlayerResponse{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaytestForPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaytestForPlayerResponse) ProtoMessage() {}

func (x *GetPlaytestForPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaytestForPlayerResponse.ProtoReflect.Descriptor instead.
func (*GetPlaytestForPlayerResponse) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{7}
}

func (x *GetPlaytestForPlayerResponse) GetPlaytest() *PlayerPlaytest {
	if x != nil {
		return x.Playtest
	}
	return nil
}

type AdminGetPlaytestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PlaytestId    string                 `protobuf:"bytes,2,opt,name=playtest_id,json=playtestId,proto3" json:"playtest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetPlaytestRequest) Reset() {
	*x = AdminGetPlaytestRequest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetPlaytestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetPlaytestRequest) ProtoMessage() {}

func (x *AdminGetPlaytestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetPlaytestRequest.ProtoReflect.Descriptor instead.
func (*AdminGetPlaytestRequest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{8}
}

func (x *AdminGetPlaytestRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AdminGetPlaytestRequest) GetPlaytestId() string {
	if x != nil {
		return x.PlaytestId
	}
	return ""
}

type AdminGetPlaytestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playtest      *Playtest              `protobuf:"bytes,1,opt,name=playtest,proto3" json:"playtest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetPlaytestResponse) Reset() {
	*x = AdminGetPlaytestResponse{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetPlaytestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetPlaytestResponse) ProtoMessage() {}

func (x *AdminGetPlaytestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetPlaytestResponse.ProtoReflect.Descriptor instead.
func (*AdminGetPlaytestResponse) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{9}
}

func (x *AdminGetPlaytestResponse) GetPlaytest() *Playtest {
	if x != nil {
		return x.Playtest
	}
	return nil
}

type ListPlaytestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlaytestsRequest) Reset() {
	*x = ListPlaytestsRequest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlaytestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlaytestsRequest) ProtoMessage() {}

func (x *ListPlaytestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlaytestsRequest.ProtoReflect.Descriptor instead.
func (*ListPlaytestsRequest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{10}
}

func (x *ListPlaytestsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListPlaytestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playtests     []*Playtest            `protobuf:"bytes,1,rep,name=playtests,proto3" json:"playtests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlaytestsResponse) Reset() {
	*x = ListPlaytestsResponse{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlaytestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlaytestsResponse) ProtoMessage() {}

func (x *ListPlaytestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlaytestsResponse.ProtoReflect.Descriptor instead.
func (*ListPlaytestsResponse) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{11}
}

func (x *ListPlaytestsResponse) GetPlaytests() []*Playtest {
	if x != nil {
		return x.Playtests
	}
	return nil
}

type CreatePlaytestRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Namespace           string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Slug                string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Title               string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description         string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	BannerImageUrl      string                 `protobuf:"bytes,5,opt,name=banner_image_url,json=bannerImageUrl,proto3" json:"banner_image_url,omitempty"`
	Platforms           []Platform             `protobuf:"varint,6,rep,packed,name=platforms,proto3,enum=playtesthub.v1.Platform" json:"platforms,omitempty"`
	StartsAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt              *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	NdaRequired         bool                   `protobuf:"varint,9,opt,name=nda_required,json=ndaRequired,proto3" json:"nda_required,omitempty"`
	NdaText             string                 `protobuf:"bytes,10,opt,name=nda_text,json=ndaText,proto3" json:"nda_text,omitempty"`
	DistributionModel   DistributionModel      `protobuf:"varint,11,opt,name=distribution_model,json=distributionModel,proto3,enum=playtesthub.v1.DistributionModel" json:"distribution_model,omitempty"`
	InitialCodeQuantity *int32                 `protobuf:"varint,12,opt,name=initial_code_quantity,json=initialCodeQuantity,proto3,oneof" json:"initial_code_quantity,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreatePlaytestRequest) Reset() {
	*x = CreatePlaytestRequest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaytestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaytestRequest) ProtoMessage() {}

func (x *CreatePlaytestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaytestRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaytestRequest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{12}
}

func (x *CreatePlaytestRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreatePlaytestRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreatePlaytestRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePlaytestRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePlaytestRequest) GetBannerImageUrl() string {
	if x != nil {
		return x.BannerImageUrl
	}
	return ""
}

func (x *CreatePlaytestRequest) GetPlatforms() []Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *CreatePlaytestRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *CreatePlaytestRequest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *CreatePlaytestRequest) GetNdaRequired() bool {
	if x != nil {
		return x.NdaRequired
	}
	return false
}

func (x *CreatePlaytestRequest) GetNdaText() string {
	if x != nil {
		return x.NdaText
	}
	return ""
}

func (x *CreatePlaytestRequest) GetDistributionModel() DistributionModel {
	if x != nil {
		return x.DistributionModel
	}
	return DistributionModel_DISTRIBUTION_MODEL_UNSPECIFIED
}

func (x *CreatePlaytestRequest) GetInitialCodeQuantity() int32 {
	if x != nil && x.InitialCodeQuantity != nil {
		return *x.InitialCodeQuantity
	}
	return 0
}

type CreatePlaytestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playtest      *Playtest              `protobuf:"bytes,1,opt,name=playtest,proto3" json:"playtest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlaytestResponse) Reset() {
	*x = CreatePlaytestResponse{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlaytestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaytestResponse) ProtoMessage() {}

func (x *CreatePlaytestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaytestResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaytestResponse) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePlaytestResponse) GetPlaytest() *Playtest {
	if x != nil {
		return x.Playtest
	}
	return nil
}

// EditPlaytestRequest mutable-field whitelist tracks PRD §5.1 L146.
// Immutable fields (slug, namespace path params excluded, status,
// distribution_model, initial_code_quantity, ags_*, timestamps) are
// deliberately absent — clients that send them on the JSON body still have
// them rejected at the handler layer.
type EditPlaytestRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PlaytestId     string                 `protobuf:"bytes,2,opt,name=playtest_id,json=playtestId,proto3" json:"playtest_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	BannerImageUrl string                 `protobuf:"bytes,5,opt,name=banner_image_url,json=bannerImageUrl,proto3" json:"banner_image_url,omitempty"`
	Platforms      []Platform             `protobuf:"varint,6,rep,packed,name=platforms,proto3,enum=playtesthub.v1.Platform" json:"platforms,omitempty"`
	StartsAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	NdaRequired    bool                   `protobuf:"varint,9,opt,name=nda_required,json=ndaRequired,proto3" json:"nda_required,omitempty"`
	NdaText        string                 `protobuf:"bytes,10,opt,name=nda_text,json=ndaText,proto3" json:"nda_text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EditPlaytestRequest) Reset() {
	*x = EditPlaytestRequest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPlaytestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPlaytestRequest) ProtoMessage() {}

func (x *EditPlaytestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPlaytestRequest.ProtoReflect.Descriptor instead.
func (*EditPlaytestRequest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{14}
}

func (x *EditPlaytestRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EditPlaytestRequest) GetPlaytestId() string {
	if x != nil {
		return x.PlaytestId
	}
	return ""
}

func (x *EditPlaytestRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditPlaytestRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EditPlaytestRequest) GetBannerImageUrl() string {
	if x != nil {
		return x.BannerImageUrl
	}
	return ""
}

func (x *EditPlaytestRequest) GetPlatforms() []Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *EditPlaytestRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *EditPlaytestRequest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *EditPlaytestRequest) GetNdaRequired() bool {
	if x != nil {
		return x.NdaRequired
	}
	return false
}

func (x *EditPlaytestRequest) GetNdaText() string {
	if x != nil {
		return x.NdaText
	}
	return ""
}

type EditPlaytestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playtest      *Playtest              `protobuf:"bytes,1,opt,name=playtest,proto3" json:"playtest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPlaytestResponse) Reset() {
	*x = EditPlaytestResponse{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPlaytestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPlaytestResponse) ProtoMessage() {}

func (x *EditPlaytestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPlaytestResponse.ProtoReflect.Descriptor instead.
func (*EditPlaytestResponse) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{15}
}

func (x *EditPlaytestResponse) GetPlaytest() *Playtest {
	if x != nil {
		return x.Playtest
	}
	return nil
}

type SoftDeletePlaytestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PlaytestId    string                 `protobuf:"bytes,2,opt,name=playtest_id,json=playtestId,proto3" json:"playtest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftDeletePlaytestRequest) Reset() {
	*x = SoftDeletePlaytestRequest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftDeletePlaytestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftDeletePlaytestRequest) ProtoMessage() {}

func (x *SoftDeletePlaytestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftDeletePlaytestRequest.ProtoReflect.Descriptor instead.
func (*SoftDeletePlaytestRequest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{16}
}

func (x *SoftDeletePlaytestRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SoftDeletePlaytestRequest) GetPlaytestId() string {
	if x != nil {
		return x.PlaytestId
	}
	return ""
}

type SoftDeletePlaytestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftDeletePlaytestResponse) Reset() {
	*x = SoftDeletePlaytestResponse{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftDeletePlaytestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftDeletePlaytestResponse) ProtoMessage() {}

func (x *SoftDeletePlaytestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftDeletePlaytestResponse.ProtoReflect.Descriptor instead.
func (*SoftDeletePlaytestResponse) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{17}
}

type TransitionPlaytestStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PlaytestId    string                 `protobuf:"bytes,2,opt,name=playtest_id,json=playtestId,proto3" json:"playtest_id,omitempty"`
	TargetStatus  PlaytestStatus         `protobuf:"varint,3,opt,name=target_status,json=targetStatus,proto3,enum=playtesthub.v1.PlaytestStatus" json:"target_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionPlaytestStatusRequest) Reset() {
	*x = TransitionPlaytestStatusRequest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionPlaytestStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionPlaytestStatusRequest) ProtoMessage() {}

func (x *TransitionPlaytestStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionPlaytestStatusRequest.ProtoReflect.Descriptor instead.
func (*TransitionPlaytestStatusRequest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{18}
}

func (x *TransitionPlaytestStatusRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TransitionPlaytestStatusRequest) GetPlaytestId() string {
	if x != nil {
		return x.PlaytestId
	}
	return ""
}

func (x *TransitionPlaytestStatusRequest) GetTargetStatus() PlaytestStatus {
	if x != nil {
		return x.TargetStatus
	}
	return PlaytestStatus_PLAYTEST_STATUS_UNSPECIFIED
}

type TransitionPlaytestStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playtest      *Playtest              `protobuf:"bytes,1,opt,name=playtest,proto3" json:"playtest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionPlaytestStatusResponse) Reset() {
	*x = TransitionPlaytestStatusResponse{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionPlaytestStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionPlaytestStatusResponse) ProtoMessage() {}

func (x *TransitionPlaytestStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionPlaytestStatusResponse.ProtoReflect.Descriptor instead.
func (*TransitionPlaytestStatusResponse) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{19}
}

func (x *TransitionPlaytestStatusResponse) GetPlaytest() *Playtest {
	if x != nil {
		return x.Playtest
	}
	return nil
}

type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Platforms     []Platform             `protobuf:"varint,2,rep,packed,name=platforms,proto3,enum=playtesthub.v1.Platform" json:"platforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{20}
}

func (x *SignupRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SignupRequest) GetPlatforms() []Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type SignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applicant     *Applicant             `protobuf:"bytes,1,opt,name=applicant,proto3" json:"applicant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupResponse) Reset() {
	*x = SignupResponse{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResponse) ProtoMessage() {}

func (x *SignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResponse.ProtoReflect.Descriptor instead.
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{21}
}

func (x *SignupResponse) GetApplicant() *Applicant {
	if x != nil {
		return x.Applicant
	}
	return nil
}

type GetApplicantStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicantStatusRequest) Reset() {
	*x = GetApplicantStatusRequest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicantStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicantStatusRequest) ProtoMessage() {}

func (x *GetApplicantStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicantStatusRequest.ProtoReflect.Descriptor instead.
func (*GetApplicantStatusRequest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{22}
}

func (x *GetApplicantStatusRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetApplicantStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applicant     *Applicant             `protobuf:"bytes,1,opt,name=applicant,proto3" json:"applicant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicantStatusResponse) Reset() {
	*x = GetApplicantStatusResponse{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicantStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicantStatusResponse) ProtoMessage() {}

func (x *GetApplicantStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicantStatusResponse.ProtoReflect.Descriptor instead.
func (*GetApplicantStatusResponse) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{23}
}

func (x *GetApplicantStatusResponse) GetApplicant() *Applicant {
	if x != nil {
		return x.Applicant
	}
	return nil
}

// ExchangeDiscordCodeRequest carries a Discord OAuth authorization code
// for the backend to exchange against AGS IAM's platform-token grant.
// The player obtained the code by driving discord.com/oauth2/authorize
// directly — AGS IAM is not involved until this RPC. The redirect_uri
// MUST byte-exactly match the value the player sent to Discord; AGS
// passes it through to Discord, which re-validates.
type ExchangeDiscordCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Discord-issued OAuth authorization code (single-use, short-lived).
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// The same redirect_uri the player sent to discord.com/oauth2/authorize.
	// Discord rejects byte-mismatches with invalid_grant.
	RedirectUri   string `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeDiscordCodeRequest) Reset() {
	*x = ExchangeDiscordCodeRequest{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeDiscordCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeDiscordCodeRequest) ProtoMessage() {}

func (x *ExchangeDiscordCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeDiscordCodeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeDiscordCodeRequest) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{24}
}

func (x *ExchangeDiscordCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExchangeDiscordCodeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type ExchangeDiscordCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AGS IAM access token (JWT) for the federated user. Player stores in
	// sessionStorage and attaches as Authorization: Bearer to player RPCs.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// AGS IAM refresh token (opaque). Forwarded as-is for future rotation.
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Lifetime of access_token in seconds, per AGS IAM response.
	ExpiresIn int32 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// Always "Bearer" today; carried verbatim for forward-compat.
	TokenType     string `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeDiscordCodeResponse) Reset() {
	*x = ExchangeDiscordCodeResponse{}
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeDiscordCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeDiscordCodeResponse) ProtoMessage() {}

func (x *ExchangeDiscordCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playtesthub_v1_playtesthub_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeDiscordCodeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeDiscordCodeResponse) Descriptor() ([]byte, []int) {
	return file_playtesthub_v1_playtesthub_proto_rawDescGZIP(), []int{25}
}

func (x *ExchangeDiscordCodeResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExchangeDiscordCodeResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ExchangeDiscordCodeResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *ExchangeDiscordCodeResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

var File_playtesthub_v1_playtesthub_proto protoreflect.FileDescriptor

const file_playtesthub_v1_playtesthub_proto_rawDesc = "" +
	"\n" +
	" playtesthub/v1/playtesthub.proto\x12\x0eplaytesthub.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fplaytesthub/v1/permission.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xff\a\n" +
	"\bPlaytest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12(\n" +
	"\x10banner_image_url\x18\x06 \x01(\tR\x0ebannerImageUrl\x126\n" +
	"\tplatforms\x18\a \x03(\x0e2\x18.playtesthub.v1.PlatformR\tplatforms\x127\n" +
	"\tstarts_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x126\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x1e.playtesthub.v1.PlaytestStatusR\x06status\x12!\n" +
	"\fnda_required\x18\v \x01(\bR\vndaRequired\x12\x19\n" +
	"\bnda_text\x18\f \x01(\tR\andaText\x127\n" +
	"\x18current_nda_version_hash\x18\r \x01(\tR\x15currentNdaVersionHash\x12 \n" +
	"\tsurvey_id\x18\x0e \x01(\tH\x00R\bsurveyId\x88\x01\x01\x12P\n" +
	"\x12distribution_model\x18\x0f \x01(\x0e2!.playtesthub.v1.DistributionModelR\x11distributionModel\x12#\n" +
	"\vags_item_id\x18\x10 \x01(\tH\x01R\tagsItemId\x88\x01\x01\x12+\n" +
	"\x0fags_campaign_id\x18\x11 \x01(\tH\x02R\ragsCampaignId\x88\x01\x01\x127\n" +
	"\x15initial_code_quantity\x18\x12 \x01(\x05H\x03R\x13initialCodeQuantity\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAtB\f\n" +
	"\n" +
	"_survey_idB\x0e\n" +
	"\f_ags_item_idB\x12\n" +
	"\x10_ags_campaign_idB\x18\n" +
	"\x16_initial_code_quantity\"\xac\x02\n" +
	"\x0ePublicPlaytest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12(\n" +
	"\x10banner_image_url\x18\x04 \x01(\tR\x0ebannerImageUrl\x126\n" +
	"\tplatforms\x18\x05 \x03(\x0e2\x18.playtesthub.v1.PlatformR\tplatforms\x127\n" +
	"\tstarts_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\"\xdd\x04\n" +
	"\x0ePlayerPlaytest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12(\n" +
	"\x10banner_image_url\x18\x04 \x01(\tR\x0ebannerImageUrl\x126\n" +
	"\tplatforms\x18\x05 \x03(\x0e2\x18.playtesthub.v1.PlatformR\tplatforms\x127\n" +
	"\tstarts_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x126\n" +
	"\x06status\x18\b \x01(\x0e2\x1e.playtesthub.v1.PlaytestStatusR\x06status\x12!\n" +
	"\fnda_required\x18\t \x01(\bR\vndaRequired\x12\x19\n" +
	"\bnda_text\x18\n" +
	" \x01(\tR\andaText\x127\n" +
	"\x18current_nda_version_hash\x18\v \x01(\tR\x15currentNdaVersionHash\x12 \n" +
	"\tsurvey_id\x18\f \x01(\tH\x00R\bsurveyId\x88\x01\x01\x12P\n" +
	"\x12distribution_model\x18\r \x01(\x0e2!.playtesthub.v1.DistributionModelR\x11distributionModelB\f\n" +
	"\n" +
	"_survey_id\"\xf3\x05\n" +
	"\tApplicant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vplaytest_id\x18\x02 \x01(\tR\n" +
	"playtestId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12%\n" +
	"\x0ediscord_handle\x18\x04 \x01(\tR\rdiscordHandle\x126\n" +
	"\tplatforms\x18\x05 \x03(\x0e2\x18.playtesthub.v1.PlatformR\tplatforms\x12-\n" +
	"\x10nda_version_hash\x18\x06 \x01(\tH\x00R\x0endaVersionHash\x88\x01\x01\x127\n" +
	"\x06status\x18\a \x01(\x0e2\x1f.playtesthub.v1.ApplicantStatusR\x06status\x12+\n" +
	"\x0fgranted_code_id\x18\b \x01(\tH\x01R\rgrantedCodeId\x88\x01\x01\x12;\n" +
	"\vapproved_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"approvedAt\x12.\n" +
	"\x10rejection_reason\x18\n" +
	" \x01(\tH\x02R\x0frejectionReason\x88\x01\x01\x12>\n" +
	"\x0elast_dm_status\x18\v \x01(\x0e2\x18.playtesthub.v1.DmStatusR\flastDmStatus\x12G\n" +
	"\x12last_dm_attempt_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0flastDmAttemptAt\x12'\n" +
	"\rlast_dm_error\x18\r \x01(\tH\x03R\vlastDmError\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x13\n" +
	"\x11_nda_version_hashB\x12\n" +
	"\x10_granted_code_idB\x13\n" +
	"\x11_rejection_reasonB\x10\n" +
	"\x0e_last_dm_error\".\n" +
	"\x18GetPublicPlaytestRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"W\n" +
	"\x19GetPublicPlaytestResponse\x12:\n" +
	"\bplaytest\x18\x01 \x01(\v2\x1e.playtesthub.v1.PublicPlaytestR\bplaytest\"1\n" +
	"\x1bGetPlaytestForPlayerRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"Z\n" +
	"\x1cGetPlaytestForPlayerResponse\x12:\n" +
	"\bplaytest\x18\x01 \x01(\v2\x1e.playtesthub.v1.PlayerPlaytestR\bplaytest\"X\n" +
	"\x17AdminGetPlaytestRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vplaytest_id\x18\x02 \x01(\tR\n" +
	"playtestId\"P\n" +
	"\x18AdminGetPlaytestResponse\x124\n" +
	"\bplaytest\x18\x01 \x01(\v2\x18.playtesthub.v1.PlaytestR\bplaytest\"4\n" +
	"\x14ListPlaytestsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"O\n" +
	"\x15ListPlaytestsResponse\x126\n" +
	"\tplaytests\x18\x01 \x03(\v2\x18.playtesthub.v1.PlaytestR\tplaytests\"\xb4\x04\n" +
	"\x15CreatePlaytestRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12(\n" +
	"\x10banner_image_url\x18\x05 \x01(\tR\x0ebannerImageUrl\x126\n" +
	"\tplatforms\x18\x06 \x03(\x0e2\x18.playtesthub.v1.PlatformR\tplatforms\x127\n" +
	"\tstarts_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12!\n" +
	"\fnda_required\x18\t \x01(\bR\vndaRequired\x12\x19\n" +
	"\bnda_text\x18\n" +
	" \x01(\tR\andaText\x12P\n" +
	"\x12distribution_model\x18\v \x01(\x0e2!.playtesthub.v1.DistributionModelR\x11distributionModel\x127\n" +
	"\x15initial_code_quantity\x18\f \x01(\x05H\x00R\x13initialCodeQuantity\x88\x01\x01B\x18\n" +
	"\x16_initial_code_quantity\"N\n" +
	"\x16CreatePlaytestResponse\x124\n" +
	"\bplaytest\x18\x01 \x01(\v2\x18.playtesthub.v1.PlaytestR\bplaytest\"\x9a\x03\n" +
	"\x13EditPlaytestRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vplaytest_id\x18\x02 \x01(\tR\n" +
	"playtestId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12(\n" +
	"\x10banner_image_url\x18\x05 \x01(\tR\x0ebannerImageUrl\x126\n" +
	"\tplatforms\x18\x06 \x03(\x0e2\x18.playtesthub.v1.PlatformR\tplatforms\x127\n" +
	"\tstarts_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12!\n" +
	"\fnda_required\x18\t \x01(\bR\vndaRequired\x12\x19\n" +
	"\bnda_text\x18\n" +
	" \x01(\tR\andaText\"L\n" +
	"\x14EditPlaytestResponse\x124\n" +
	"\bplaytest\x18\x01 \x01(\v2\x18.playtesthub.v1.PlaytestR\bplaytest\"Z\n" +
	"\x19SoftDeletePlaytestRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vplaytest_id\x18\x02 \x01(\tR\n" +
	"playtestId\"\x1c\n" +
	"\x1aSoftDeletePlaytestResponse\"\xa5\x01\n" +
	"\x1fTransitionPlaytestStatusRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vplaytest_id\x18\x02 \x01(\tR\n" +
	"playtestId\x12C\n" +
	"\rtarget_status\x18\x03 \x01(\x0e2\x1e.playtesthub.v1.PlaytestStatusR\ftargetStatus\"X\n" +
	" TransitionPlaytestStatusResponse\x124\n" +
	"\bplaytest\x18\x01 \x01(\v2\x18.playtesthub.v1.PlaytestR\bplaytest\"[\n" +
	"\rSignupRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x126\n" +
	"\tplatforms\x18\x02 \x03(\x0e2\x18.playtesthub.v1.PlatformR\tplatforms\"I\n" +
	"\x0eSignupResponse\x127\n" +
	"\tapplicant\x18\x01 \x01(\v2\x19.playtesthub.v1.ApplicantR\tapplicant\"/\n" +
	"\x19GetApplicantStatusRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"U\n" +
	"\x1aGetApplicantStatusResponse\x127\n" +
	"\tapplicant\x18\x01 \x01(\v2\x19.playtesthub.v1.ApplicantR\tapplicant\"S\n" +
	"\x1aExchangeDiscordCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\"\xa3\x01\n" +
	"\x1bExchangeDiscordCodeResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType*\x8c\x01\n" +
	"\bPlatform\x12\x18\n" +
	"\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePLATFORM_STEAM\x10\x01\x12\x11\n" +
	"\rPLATFORM_XBOX\x10\x02\x12\x18\n" +
	"\x14PLATFORM_PLAYSTATION\x10\x03\x12\x11\n" +
	"\rPLATFORM_EPIC\x10\x04\x12\x12\n" +
	"\x0ePLATFORM_OTHER\x10\x05*\x82\x01\n" +
	"\x0ePlaytestStatus\x12\x1f\n" +
	"\x1bPLAYTEST_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PLAYTEST_STATUS_DRAFT\x10\x01\x12\x18\n" +
	"\x14PLAYTEST_STATUS_OPEN\x10\x02\x12\x1a\n" +
	"\x16PLAYTEST_STATUS_CLOSED\x10\x03*\x7f\n" +
	"\x11DistributionModel\x12\"\n" +
	"\x1eDISTRIBUTION_MODEL_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dDISTRIBUTION_MODEL_STEAM_KEYS\x10\x01\x12#\n" +
	"\x1fDISTRIBUTION_MODEL_AGS_CAMPAIGN\x10\x02*\x8f\x01\n" +
	"\x0fApplicantStatus\x12 \n" +
	"\x1cAPPLICANT_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18APPLICANT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19APPLICANT_STATUS_APPROVED\x10\x02\x12\x1d\n" +
	"\x19APPLICANT_STATUS_REJECTED\x10\x03*O\n" +
	"\bDmStatus\x12\x19\n" +
	"\x15DM_STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDM_STATUS_SENT\x10\x01\x12\x14\n" +
	"\x10DM_STATUS_FAILED\x10\x022\xb8\x1e\n" +
	"\x12PlaytesthubService\x12\xa0\x02\n" +
	"\x11GetPublicPlaytest\x12(.playtesthub.v1.GetPublicPlaytestRequest\x1a).playtesthub.v1.GetPublicPlaytestResponse\"\xb5\x01\x92A\x8e\x01\x12(Get a playtest by slug (unauthenticated)\x1abReturns the public field subset for an OPEN playtest. NotFound for DRAFT, CLOSED, or soft-deleted.\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/public/playtests/{slug}\x12\xac\x02\n" +
	"\x14GetPlaytestForPlayer\x12+.playtesthub.v1.GetPlaytestForPlayerRequest\x1a,.playtesthub.v1.GetPlaytestForPlayerResponse\"\xb8\x01\x92A\x91\x01\x12-Get a playtest by slug (authenticated player)\x1aRReturns the player-visible field set including NDA text and currentNdaVersionHash.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/player/playtests/{slug}\x12\x87\x02\n" +
	"\x10AdminGetPlaytest\x12'.playtesthub.v1.AdminGetPlaytestRequest\x1a(.playtesthub.v1.AdminGetPlaytestResponse\"\x9f\x01\x92A,\x12\x1cGet a playtest by ID (admin)b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18(ADMIN:NAMESPACE:{namespace}:EXTEND:APPUI\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02:\x128/v1/admin/namespaces/{namespace}/playtests/{playtest_id}\x12\x94\x02\n" +
	"\rListPlaytests\x12$.playtesthub.v1.ListPlaytestsRequest\x1a%.playtesthub.v1.ListPlaytestsResponse\"\xb5\x01\x92AP\x12@List playtests in a namespace (admin, unpaginated; 100-item cap)b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18(ADMIN:NAMESPACE:{namespace}:EXTEND:APPUI\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02,\x12*/v1/admin/namespaces/{namespace}/playtests\x12\xcc\x02\n" +
	"\x0eCreatePlaytest\x12%.playtesthub.v1.CreatePlaytestRequest\x1a&.playtesthub.v1.CreatePlaytestResponse\"\xea\x01\x92A\x81\x01\x12\x19Create a playtest (admin)\x1aVSTEAM_KEYS only in M1; distribution_model=AGS_CAMPAIGN returns Unimplemented until M2.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18(ADMIN:NAMESPACE:{namespace}:EXTEND:APPUI\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/admin/namespaces/{namespace}/playtests\x12\x95\x03\n" +
	"\fEditPlaytest\x12#.playtesthub.v1.EditPlaytestRequest\x1a$.playtesthub.v1.EditPlaytestResponse\"\xb9\x02\x92A\xc2\x01\x12)Edit mutable fields on a playtest (admin)\x1a\x86\x01Editable: title, description, bannerImageUrl, platforms, startsAt, endsAt, ndaRequired, ndaText. Immutable fields → InvalidArgument.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18(ADMIN:NAMESPACE:{namespace}:EXTEND:APPUI\x90\xb5\x18\x04\x82\xd3\xe4\x93\x02=:\x01*28/v1/admin/namespaces/{namespace}/playtests/{playtest_id}\x12\xa9\x02\n" +
	"\x12SoftDeletePlaytest\x12).playtesthub.v1.SoftDeletePlaytestRequest\x1a*.playtesthub.v1.SoftDeletePlaytestResponse\"\xbb\x01\x92AH\x128Soft-delete a playtest (admin; idempotent, irreversible)b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18(ADMIN:NAMESPACE:{namespace}:EXTEND:APPUI\x90\xb5\x18\b\x82\xd3\xe4\x93\x02:*8/v1/admin/namespaces/{namespace}/playtests/{playtest_id}\x12\xd9\x02\n" +
	"\x18TransitionPlaytestStatus\x12/.playtesthub.v1.TransitionPlaytestStatusRequest\x1a0.playtesthub.v1.TransitionPlaytestStatusResponse\"\xd9\x01\x92AR\x12BTransition a playtest's status (admin; DRAFT→OPEN→CLOSED only)b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18(ADMIN:NAMESPACE:{namespace}:EXTEND:APPUI\x90\xb5\x18\x04\x82\xd3\xe4\x93\x02N:\x01*\"I/v1/admin/namespaces/{namespace}/playtests/{playtest_id}:transitionStatus\x12\x80\a\n" +
	"\x13ExchangeDiscordCode\x12*.playtesthub.v1.ExchangeDiscordCodeRequest\x1a+.playtesthub.v1.ExchangeDiscordCodeResponse\"\x8f\x06\x92A\xe5\x05\x12UExchange a Discord OAuth authorization code for an AGS access token (unauthenticated)\x1a\x8b\x05Player runs Discord OAuth directly (Discord developer portal owns the redirect-URI allowlist). The resulting Discord authorization code is POSTed here; the backend authenticates with confidential AGS IAM credentials and calls /iam/v3/oauth/platforms/discord/token (platform-token grant). AGS auto-creates the Justice platform account on first call and returns AGS access + refresh tokens, which we forward verbatim. Replaces the auth-code federation flow attempted in STATUS.md M1 phase 9.2 — that flow's /iam/v3/oauth/token step always failed with invalid_grant in game namespaces because the auth-code path skips Justice-platform-account creation.\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/player/discord/exchange\x12\xdb\x01\n" +
	"\x06Signup\x12\x1d.playtesthub.v1.SignupRequest\x1a\x1e.playtesthub.v1.SignupResponse\"\x91\x01\x92Aa\x12QSign up for a playtest (authenticated player; idempotent on (playtestId, userId))b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/player/playtests/{slug}/signup\x12\xde\x01\n" +
	"\x12GetApplicantStatus\x12).playtesthub.v1.GetApplicantStatusRequest\x1a*.playtesthub.v1.GetApplicantStatusResponse\"q\x92AA\x121Get the caller's own applicant row for a playtestb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02'\x12%/v1/player/playtests/{slug}/applicantB\x94\x01\x92AF\x12\x15\n" +
	"\x0fplaytesthub API2\x02v1\"\f/playtesthubZ\x1f\n" +
	"\x1d\n" +
	"\x06Bearer\x12\x13\b\x02\x1a\rAuthorization \x02ZIgithub.com/anggorodewanto/playtesthub/pkg/pb/playtesthub/v1;playtesthubv1b\x06proto3"

var (
	file_playtesthub_v1_playtesthub_proto_rawDescOnce sync.Once
	file_playtesthub_v1_playtesthub_proto_rawDescData []byte
)

func file_playtesthub_v1_playtesthub_proto_rawDescGZIP() []byte {
	file_playtesthub_v1_playtesthub_proto_rawDescOnce.Do(func() {
		file_playtesthub_v1_playtesthub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_playtesthub_v1_playtesthub_proto_rawDesc), len(file_playtesthub_v1_playtesthub_proto_rawDesc)))
	})
	return file_playtesthub_v1_playtesthub_proto_rawDescData
}

var file_playtesthub_v1_playtesthub_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_playtesthub_v1_playtesthub_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_playtesthub_v1_playtesthub_proto_goTypes = []any{
	(Platform)(0),                            // 0: playtesthub.v1.Platform
	(PlaytestStatus)(0),                      // 1: playtesthub.v1.PlaytestStatus
	(DistributionModel)(0),                   // 2: playtesthub.v1.DistributionModel
	(ApplicantStatus)(0),                     // 3: playtesthub.v1.ApplicantStatus
	(DmStatus)(0),                            // 4: playtesthub.v1.DmStatus
	(*Playtest)(nil),                         // 5: playtesthub.v1.Playtest
	(*PublicPlaytest)(nil),                   // 6: playtesthub.v1.PublicPlaytest
	(*PlayerPlaytest)(nil),                   // 7: playtesthub.v1.PlayerPlaytest
	(*Applicant)(nil),                        // 8: playtesthub.v1.Applicant
	(*GetPublicPlaytestRequest)(nil),         // 9: playtesthub.v1.GetPublicPlaytestRequest
	(*GetPublicPlaytestResponse)(nil),        // 10: playtesthub.v1.GetPublicPlaytestResponse
	(*GetPlaytestForPlayerRequest)(nil),      // 11: playtesthub.v1.GetPlaytestForPlayerRequest
	(*GetPlaytestForPlayerResponse)(nil),     // 12: playtesthub.v1.GetPlaytestForPlayerResponse
	(*AdminGetPlaytestRequest)(nil),          // 13: playtesthub.v1.AdminGetPlaytestRequest
	(*AdminGetPlaytestResponse)(nil),         // 14: playtesthub.v1.AdminGetPlaytestResponse
	(*ListPlaytestsRequest)(nil),             // 15: playtesthub.v1.ListPlaytestsRequest
	(*ListPlaytestsResponse)(nil),            // 16: playtesthub.v1.ListPlaytestsResponse
	(*CreatePlaytestRequest)(nil),            // 17: playtesthub.v1.CreatePlaytestRequest
	(*CreatePlaytestResponse)(nil),           // 18: playtesthub.v1.CreatePlaytestResponse
	(*EditPlaytestRequest)(nil),              // 19: playtesthub.v1.EditPlaytestRequest
	(*EditPlaytestResponse)(nil),             // 20: playtesthub.v1.EditPlaytestResponse
	(*SoftDeletePlaytestRequest)(nil),        // 21: playtesthub.v1.SoftDeletePlaytestRequest
	(*SoftDeletePlaytestResponse)(nil),       // 22: playtesthub.v1.SoftDeletePlaytestResponse
	(*TransitionPlaytestStatusRequest)(nil),  // 23: playtesthub.v1.TransitionPlaytestStatusRequest
	(*TransitionPlaytestStatusResponse)(nil), // 24: playtesthub.v1.TransitionPlaytestStatusResponse
	(*SignupRequest)(nil),                    // 25: playtesthub.v1.SignupRequest
	(*SignupResponse)(nil),                   // 26: playtesthub.v1.SignupResponse
	(*GetApplicantStatusRequest)(nil),        // 27: playtesthub.v1.GetApplicantStatusRequest
	(*GetApplicantStatusResponse)(nil),       // 28: playtesthub.v1.GetApplicantStatusResponse
	(*ExchangeDiscordCodeRequest)(nil),       // 29: playtesthub.v1.ExchangeDiscordCodeRequest
	(*ExchangeDiscordCodeResponse)(nil),      // 30: playtesthub.v1.ExchangeDiscordCodeResponse
	(*timestamppb.Timestamp)(nil),            // 31: google.protobuf.Timestamp
}
var file_playtesthub_v1_playtesthub_proto_depIdxs = []int32{
	0,  // 0: playtesthub.v1.Playtest.platforms:type_name -> playtesthub.v1.Platform
	31, // 1: playtesthub.v1.Playtest.starts_at:type_name -> google.protobuf.Timestamp
	31, // 2: playtesthub.v1.Playtest.ends_at:type_name -> google.protobuf.Timestamp
	1,  // 3: playtesthub.v1.Playtest.status:type_name -> playtesthub.v1.PlaytestStatus
	2,  // 4: playtesthub.v1.Playtest.distribution_model:type_name -> playtesthub.v1.DistributionModel
	31, // 5: playtesthub.v1.Playtest.created_at:type_name -> google.protobuf.Timestamp
	31, // 6: playtesthub.v1.Playtest.updated_at:type_name -> google.protobuf.Timestamp
	31, // 7: playtesthub.v1.Playtest.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 8: playtesthub.v1.PublicPlaytest.platforms:type_name -> playtesthub.v1.Platform
	31, // 9: playtesthub.v1.PublicPlaytest.starts_at:type_name -> google.protobuf.Timestamp
	31, // 10: playtesthub.v1.PublicPlaytest.ends_at:type_name -> google.protobuf.Timestamp
	0,  // 11: playtesthub.v1.PlayerPlaytest.platforms:type_name -> playtesthub.v1.Platform
	31, // 12: playtesthub.v1.PlayerPlaytest.starts_at:type_name -> google.protobuf.Timestamp
	31, // 13: playtesthub.v1.PlayerPlaytest.ends_at:type_name -> google.protobuf.Timestamp
	1,  // 14: playtesthub.v1.PlayerPlaytest.status:type_name -> playtesthub.v1.PlaytestStatus
	2,  // 15: playtesthub.v1.PlayerPlaytest.distribution_model:type_name -> playtesthub.v1.DistributionModel
	0,  // 16: playtesthub.v1.Applicant.platforms:type_name -> playtesthub.v1.Platform
	3,  // 17: playtesthub.v1.Applicant.status:type_name -> playtesthub.v1.ApplicantStatus
	31, // 18: playtesthub.v1.Applicant.approved_at:type_name -> google.protobuf.Timestamp
	4,  // 19: playtesthub.v1.Applicant.last_dm_status:type_name -> playtesthub.v1.DmStatus
	31, // 20: playtesthub.v1.Applicant.last_dm_attempt_at:type_name -> google.protobuf.Timestamp
	31, // 21: playtesthub.v1.Applicant.created_at:type_name -> google.protobuf.Timestamp
	6,  // 22: playtesthub.v1.GetPublicPlaytestResponse.playtest:type_name -> playtesthub.v1.PublicPlaytest
	7,  // 23: playtesthub.v1.GetPlaytestForPlayerResponse.playtest:type_name -> playtesthub.v1.PlayerPlaytest
	5,  // 24: playtesthub.v1.AdminGetPlaytestResponse.playtest:type_name -> playtesthub.v1.Playtest
	5,  // 25: playtesthub.v1.ListPlaytestsResponse.playtests:type_name -> playtesthub.v1.Playtest
	0,  // 26: playtesthub.v1.CreatePlaytestRequest.platforms:type_name -> playtesthub.v1.Platform
	31, // 27: playtesthub.v1.CreatePlaytestRequest.starts_at:type_name -> google.protobuf.Timestamp
	31, // 28: playtesthub.v1.CreatePlaytestRequest.ends_at:type_name -> google.protobuf.Timestamp
	2,  // 29: playtesthub.v1.CreatePlaytestRequest.distribution_model:type_name -> playtesthub.v1.DistributionModel
	5,  // 30: playtesthub.v1.CreatePlaytestResponse.playtest:type_name -> playtesthub.v1.Playtest
	0,  // 31: playtesthub.v1.EditPlaytestRequest.platforms:type_name -> playtesthub.v1.Platform
	31, // 32: playtesthub.v1.EditPlaytestRequest.starts_at:type_name -> google.protobuf.Timestamp
	31, // 33: playtesthub.v1.EditPlaytestRequest.ends_at:type_name -> google.protobuf.Timestamp
	5,  // 34: playtesthub.v1.EditPlaytestResponse.playtest:type_name -> playtesthub.v1.Playtest
	1,  // 35: playtesthub.v1.TransitionPlaytestStatusRequest.target_status:type_name -> playtesthub.v1.PlaytestStatus
	5,  // 36: playtesthub.v1.TransitionPlaytestStatusResponse.playtest:type_name -> playtesthub.v1.Playtest
	0,  // 37: playtesthub.v1.SignupRequest.platforms:type_name -> playtesthub.v1.Platform
	8,  // 38: playtesthub.v1.SignupResponse.applicant:type_name -> playtesthub.v1.Applicant
	8,  // 39: playtesthub.v1.GetApplicantStatusResponse.applicant:type_name -> playtesthub.v1.Applicant
	9,  // 40: playtesthub.v1.PlaytesthubService.GetPublicPlaytest:input_type -> playtesthub.v1.GetPublicPlaytestRequest
	11, // 41: playtesthub.v1.PlaytesthubService.GetPlaytestForPlayer:input_type -> playtesthub.v1.GetPlaytestForPlayerRequest
	13, // 42: playtesthub.v1.PlaytesthubService.AdminGetPlaytest:input_type -> playtesthub.v1.AdminGetPlaytestRequest
	15, // 43: playtesthub.v1.PlaytesthubService.ListPlaytests:input_type -> playtesthub.v1.ListPlaytestsRequest
	17, // 44: playtesthub.v1.PlaytesthubService.CreatePlaytest:input_type -> playtesthub.v1.CreatePlaytestRequest
	19, // 45: playtesthub.v1.PlaytesthubService.EditPlaytest:input_type -> playtesthub.v1.EditPlaytestRequest
	21, // 46: playtesthub.v1.PlaytesthubService.SoftDeletePlaytest:input_type -> playtesthub.v1.SoftDeletePlaytestRequest
	23, // 47: playtesthub.v1.PlaytesthubService.TransitionPlaytestStatus:input_type -> playtesthub.v1.TransitionPlaytestStatusRequest
	29, // 48: playtesthub.v1.PlaytesthubService.ExchangeDiscordCode:input_type -> playtesthub.v1.ExchangeDiscordCodeRequest
	25, // 49: playtesthub.v1.PlaytesthubService.Signup:input_type -> playtesthub.v1.SignupRequest
	27, // 50: playtesthub.v1.PlaytesthubService.GetApplicantStatus:input_type -> playtesthub.v1.GetApplicantStatusRequest
	10, // 51: playtesthub.v1.PlaytesthubService.GetPublicPlaytest:output_type -> playtesthub.v1.GetPublicPlaytestResponse
	12, // 52: playtesthub.v1.PlaytesthubService.GetPlaytestForPlayer:output_type -> playtesthub.v1.GetPlaytestForPlayerResponse
	14, // 53: playtesthub.v1.PlaytesthubService.AdminGetPlaytest:output_type -> playtesthub.v1.AdminGetPlaytestResponse
	16, // 54: playtesthub.v1.PlaytesthubService.ListPlaytests:output_type -> playtesthub.v1.ListPlaytestsResponse
	18, // 55: playtesthub.v1.PlaytesthubService.CreatePlaytest:output_type -> playtesthub.v1.CreatePlaytestResponse
	20, // 56: playtesthub.v1.PlaytesthubService.EditPlaytest:output_type -> playtesthub.v1.EditPlaytestResponse
	22, // 57: playtesthub.v1.PlaytesthubService.SoftDeletePlaytest:output_type -> playtesthub.v1.SoftDeletePlaytestResponse
	24, // 58: playtesthub.v1.PlaytesthubService.TransitionPlaytestStatus:output_type -> playtesthub.v1.TransitionPlaytestStatusResponse
	30, // 59: playtesthub.v1.PlaytesthubService.ExchangeDiscordCode:output_type -> playtesthub.v1.ExchangeDiscordCodeResponse
	26, // 60: playtesthub.v1.PlaytesthubService.Signup:output_type -> playtesthub.v1.SignupResponse
	28, // 61: playtesthub.v1.PlaytesthubService.GetApplicantStatus:output_type -> playtesthub.v1.GetApplicantStatusResponse
	51, // [51:62] is the sub-list for method output_type
	40, // [40:51] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_playtesthub_v1_playtesthub_proto_init() }
func file_playtesthub_v1_playtesthub_proto_init() {
	if File_playtesthub_v1_playtesthub_proto != nil {
		return
	}
	file_playtesthub_v1_permission_proto_init()
	file_playtesthub_v1_playtesthub_proto_msgTypes[0].OneofWrappers = []any{}
	file_playtesthub_v1_playtesthub_proto_msgTypes[2].OneofWrappers = []any{}
	file_playtesthub_v1_playtesthub_proto_msgTypes[3].OneofWrappers = []any{}
	file_playtesthub_v1_playtesthub_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_playtesthub_v1_playtesthub_proto_rawDesc), len(file_playtesthub_v1_playtesthub_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_playtesthub_v1_playtesthub_proto_goTypes,
		DependencyIndexes: file_playtesthub_v1_playtesthub_proto_depIdxs,
		EnumInfos:         file_playtesthub_v1_playtesthub_proto_enumTypes,
		MessageInfos:      file_playtesthub_v1_playtesthub_proto_msgTypes,
	}.Build()
	File_playtesthub_v1_playtesthub_proto = out.File
	file_playtesthub_v1_playtesthub_proto_goTypes = nil
	file_playtesthub_v1_playtesthub_proto_depIdxs = nil
}
