// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: playtesthub/v1/playtesthub.proto

package playtesthubv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlaytesthubService_GetPublicPlaytest_FullMethodName        = "/playtesthub.v1.PlaytesthubService/GetPublicPlaytest"
	PlaytesthubService_GetPublicConfig_FullMethodName          = "/playtesthub.v1.PlaytesthubService/GetPublicConfig"
	PlaytesthubService_GetPlaytestForPlayer_FullMethodName     = "/playtesthub.v1.PlaytesthubService/GetPlaytestForPlayer"
	PlaytesthubService_WhoAmI_FullMethodName                   = "/playtesthub.v1.PlaytesthubService/WhoAmI"
	PlaytesthubService_AdminGetPlaytest_FullMethodName         = "/playtesthub.v1.PlaytesthubService/AdminGetPlaytest"
	PlaytesthubService_ListPlaytests_FullMethodName            = "/playtesthub.v1.PlaytesthubService/ListPlaytests"
	PlaytesthubService_CreatePlaytest_FullMethodName           = "/playtesthub.v1.PlaytesthubService/CreatePlaytest"
	PlaytesthubService_EditPlaytest_FullMethodName             = "/playtesthub.v1.PlaytesthubService/EditPlaytest"
	PlaytesthubService_SoftDeletePlaytest_FullMethodName       = "/playtesthub.v1.PlaytesthubService/SoftDeletePlaytest"
	PlaytesthubService_TransitionPlaytestStatus_FullMethodName = "/playtesthub.v1.PlaytesthubService/TransitionPlaytestStatus"
	PlaytesthubService_ExchangeDiscordCode_FullMethodName      = "/playtesthub.v1.PlaytesthubService/ExchangeDiscordCode"
	PlaytesthubService_Signup_FullMethodName                   = "/playtesthub.v1.PlaytesthubService/Signup"
	PlaytesthubService_GetApplicantStatus_FullMethodName       = "/playtesthub.v1.PlaytesthubService/GetApplicantStatus"
	PlaytesthubService_AcceptNDA_FullMethodName                = "/playtesthub.v1.PlaytesthubService/AcceptNDA"
	PlaytesthubService_GetGrantedCode_FullMethodName           = "/playtesthub.v1.PlaytesthubService/GetGrantedCode"
	PlaytesthubService_GetADTDownloadInfo_FullMethodName       = "/playtesthub.v1.PlaytesthubService/GetADTDownloadInfo"
	PlaytesthubService_ListApplicants_FullMethodName           = "/playtesthub.v1.PlaytesthubService/ListApplicants"
	PlaytesthubService_ApproveApplicant_FullMethodName         = "/playtesthub.v1.PlaytesthubService/ApproveApplicant"
	PlaytesthubService_RejectApplicant_FullMethodName          = "/playtesthub.v1.PlaytesthubService/RejectApplicant"
	PlaytesthubService_RetryDM_FullMethodName                  = "/playtesthub.v1.PlaytesthubService/RetryDM"
	PlaytesthubService_UploadCodes_FullMethodName              = "/playtesthub.v1.PlaytesthubService/UploadCodes"
	PlaytesthubService_TopUpCodes_FullMethodName               = "/playtesthub.v1.PlaytesthubService/TopUpCodes"
	PlaytesthubService_SyncFromAGS_FullMethodName              = "/playtesthub.v1.PlaytesthubService/SyncFromAGS"
	PlaytesthubService_GetCodePool_FullMethodName              = "/playtesthub.v1.PlaytesthubService/GetCodePool"
	PlaytesthubService_CreateSurvey_FullMethodName             = "/playtesthub.v1.PlaytesthubService/CreateSurvey"
	PlaytesthubService_EditSurvey_FullMethodName               = "/playtesthub.v1.PlaytesthubService/EditSurvey"
	PlaytesthubService_GetSurvey_FullMethodName                = "/playtesthub.v1.PlaytesthubService/GetSurvey"
	PlaytesthubService_SubmitSurveyResponse_FullMethodName     = "/playtesthub.v1.PlaytesthubService/SubmitSurveyResponse"
	PlaytesthubService_ListSurveyResponses_FullMethodName      = "/playtesthub.v1.PlaytesthubService/ListSurveyResponses"
	PlaytesthubService_ListAuditLog_FullMethodName             = "/playtesthub.v1.PlaytesthubService/ListAuditLog"
	PlaytesthubService_RetryFailedDms_FullMethodName           = "/playtesthub.v1.PlaytesthubService/RetryFailedDms"
	PlaytesthubService_GetWorkerHealth_FullMethodName          = "/playtesthub.v1.PlaytesthubService/GetWorkerHealth"
	PlaytesthubService_ListADTLinkages_FullMethodName          = "/playtesthub.v1.PlaytesthubService/ListADTLinkages"
	PlaytesthubService_StartADTLink_FullMethodName             = "/playtesthub.v1.PlaytesthubService/StartADTLink"
	PlaytesthubService_CompleteADTLink_FullMethodName          = "/playtesthub.v1.PlaytesthubService/CompleteADTLink"
	PlaytesthubService_UnlinkADT_FullMethodName                = "/playtesthub.v1.PlaytesthubService/UnlinkADT"
	PlaytesthubService_RecoverADTLinkage_FullMethodName        = "/playtesthub.v1.PlaytesthubService/RecoverADTLinkage"
	PlaytesthubService_ListADTBuilds_FullMethodName            = "/playtesthub.v1.PlaytesthubService/ListADTBuilds"
	PlaytesthubService_ListADTGames_FullMethodName             = "/playtesthub.v1.PlaytesthubService/ListADTGames"
	PlaytesthubService_GetADTClientDiagnostics_FullMethodName  = "/playtesthub.v1.PlaytesthubService/GetADTClientDiagnostics"
	PlaytesthubService_GetPlaytestParticipants_FullMethodName  = "/playtesthub.v1.PlaytesthubService/GetPlaytestParticipants"
	PlaytesthubService_CreateAnnouncement_FullMethodName       = "/playtesthub.v1.PlaytesthubService/CreateAnnouncement"
	PlaytesthubService_ListAnnouncements_FullMethodName        = "/playtesthub.v1.PlaytesthubService/ListAnnouncements"
)

// PlaytesthubServiceClient is the client API for PlaytesthubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlaytesthubService carries every playtesthub RPC. Auth is differentiated
// per-method via OpenAPI Bearer security blocks and permission.action /
// permission.resource options — inspected by the server's auth interceptor
// (pkg/common/authServerInterceptor.go).
//
//   - Unauth    : no Bearer security, no permission.* options.
//   - Player    : Bearer security only. Any authed AGS IAM user.
//   - Admin     : Bearer security + permission.resource + permission.action.
//     MVP authorizes any authed admin session (PRD §9 R8); the
//     permission option still carries the AGS-style resource string
//     so future RBAC can plug in without a proto change.
type PlaytesthubServiceClient interface {
	GetPublicPlaytest(ctx context.Context, in *GetPublicPlaytestRequest, opts ...grpc.CallOption) (*GetPublicPlaytestResponse, error)
	GetPublicConfig(ctx context.Context, in *GetPublicConfigRequest, opts ...grpc.CallOption) (*GetPublicConfigResponse, error)
	GetPlaytestForPlayer(ctx context.Context, in *GetPlaytestForPlayerRequest, opts ...grpc.CallOption) (*GetPlaytestForPlayerResponse, error)
	WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error)
	AdminGetPlaytest(ctx context.Context, in *AdminGetPlaytestRequest, opts ...grpc.CallOption) (*AdminGetPlaytestResponse, error)
	ListPlaytests(ctx context.Context, in *ListPlaytestsRequest, opts ...grpc.CallOption) (*ListPlaytestsResponse, error)
	CreatePlaytest(ctx context.Context, in *CreatePlaytestRequest, opts ...grpc.CallOption) (*CreatePlaytestResponse, error)
	EditPlaytest(ctx context.Context, in *EditPlaytestRequest, opts ...grpc.CallOption) (*EditPlaytestResponse, error)
	SoftDeletePlaytest(ctx context.Context, in *SoftDeletePlaytestRequest, opts ...grpc.CallOption) (*SoftDeletePlaytestResponse, error)
	TransitionPlaytestStatus(ctx context.Context, in *TransitionPlaytestStatusRequest, opts ...grpc.CallOption) (*TransitionPlaytestStatusResponse, error)
	ExchangeDiscordCode(ctx context.Context, in *ExchangeDiscordCodeRequest, opts ...grpc.CallOption) (*ExchangeDiscordCodeResponse, error)
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	GetApplicantStatus(ctx context.Context, in *GetApplicantStatusRequest, opts ...grpc.CallOption) (*GetApplicantStatusResponse, error)
	AcceptNDA(ctx context.Context, in *AcceptNDARequest, opts ...grpc.CallOption) (*AcceptNDAResponse, error)
	GetGrantedCode(ctx context.Context, in *GetGrantedCodeRequest, opts ...grpc.CallOption) (*GetGrantedCodeResponse, error)
	// GetADTDownloadInfo — ADT-distribution equivalent of GetGrantedCode
	// (PRD §4.8 / M5.B). Player-only; gated on APPROVED applicant row.
	GetADTDownloadInfo(ctx context.Context, in *GetADTDownloadInfoRequest, opts ...grpc.CallOption) (*GetADTDownloadInfoResponse, error)
	ListApplicants(ctx context.Context, in *ListApplicantsRequest, opts ...grpc.CallOption) (*ListApplicantsResponse, error)
	ApproveApplicant(ctx context.Context, in *ApproveApplicantRequest, opts ...grpc.CallOption) (*ApproveApplicantResponse, error)
	RejectApplicant(ctx context.Context, in *RejectApplicantRequest, opts ...grpc.CallOption) (*RejectApplicantResponse, error)
	RetryDM(ctx context.Context, in *RetryDMRequest, opts ...grpc.CallOption) (*RetryDMResponse, error)
	UploadCodes(ctx context.Context, in *UploadCodesRequest, opts ...grpc.CallOption) (*UploadCodesResponse, error)
	TopUpCodes(ctx context.Context, in *TopUpCodesRequest, opts ...grpc.CallOption) (*TopUpCodesResponse, error)
	SyncFromAGS(ctx context.Context, in *SyncFromAGSRequest, opts ...grpc.CallOption) (*SyncFromAGSResponse, error)
	GetCodePool(ctx context.Context, in *GetCodePoolRequest, opts ...grpc.CallOption) (*GetCodePoolResponse, error)
	CreateSurvey(ctx context.Context, in *CreateSurveyRequest, opts ...grpc.CallOption) (*CreateSurveyResponse, error)
	EditSurvey(ctx context.Context, in *EditSurveyRequest, opts ...grpc.CallOption) (*EditSurveyResponse, error)
	GetSurvey(ctx context.Context, in *GetSurveyRequest, opts ...grpc.CallOption) (*GetSurveyResponse, error)
	SubmitSurveyResponse(ctx context.Context, in *SubmitSurveyResponseRequest, opts ...grpc.CallOption) (*SubmitSurveyResponseResponse, error)
	ListSurveyResponses(ctx context.Context, in *ListSurveyResponsesRequest, opts ...grpc.CallOption) (*ListSurveyResponsesResponse, error)
	ListAuditLog(ctx context.Context, in *ListAuditLogRequest, opts ...grpc.CallOption) (*ListAuditLogResponse, error)
	RetryFailedDms(ctx context.Context, in *RetryFailedDmsRequest, opts ...grpc.CallOption) (*RetryFailedDmsResponse, error)
	GetWorkerHealth(ctx context.Context, in *GetWorkerHealthRequest, opts ...grpc.CallOption) (*GetWorkerHealthResponse, error)
	ListADTLinkages(ctx context.Context, in *ListADTLinkagesRequest, opts ...grpc.CallOption) (*ListADTLinkagesResponse, error)
	StartADTLink(ctx context.Context, in *StartADTLinkRequest, opts ...grpc.CallOption) (*StartADTLinkResponse, error)
	CompleteADTLink(ctx context.Context, in *CompleteADTLinkRequest, opts ...grpc.CallOption) (*CompleteADTLinkResponse, error)
	UnlinkADT(ctx context.Context, in *UnlinkADTRequest, opts ...grpc.CallOption) (*UnlinkADTResponse, error)
	RecoverADTLinkage(ctx context.Context, in *RecoverADTLinkageRequest, opts ...grpc.CallOption) (*RecoverADTLinkageResponse, error)
	ListADTBuilds(ctx context.Context, in *ListADTBuildsRequest, opts ...grpc.CallOption) (*ListADTBuildsResponse, error)
	ListADTGames(ctx context.Context, in *ListADTGamesRequest, opts ...grpc.CallOption) (*ListADTGamesResponse, error)
	GetADTClientDiagnostics(ctx context.Context, in *GetADTClientDiagnosticsRequest, opts ...grpc.CallOption) (*GetADTClientDiagnosticsResponse, error)
	// M5.C — participants surface backing the detail page Participants tab.
	// Cache-only read; the four ADT telemetry cache columns ship dormant in
	// M5.C (NULL/zero across the milestone — M6 lights them up).
	GetPlaytestParticipants(ctx context.Context, in *GetPlaytestParticipantsRequest, opts ...grpc.CallOption) (*GetPlaytestParticipantsResponse, error)
	// M5.C — bulk announcement broadcast (PRD §5.4 "Bulk announcements").
	// Resolves the recipient set at call time; fans out via the existing
	// M2 RetryDM machinery.
	CreateAnnouncement(ctx context.Context, in *CreateAnnouncementRequest, opts ...grpc.CallOption) (*CreateAnnouncementResponse, error)
	ListAnnouncements(ctx context.Context, in *ListAnnouncementsRequest, opts ...grpc.CallOption) (*ListAnnouncementsResponse, error)
}

type playtesthubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaytesthubServiceClient(cc grpc.ClientConnInterface) PlaytesthubServiceClient {
	return &playtesthubServiceClient{cc}
}

func (c *playtesthubServiceClient) GetPublicPlaytest(ctx context.Context, in *GetPublicPlaytestRequest, opts ...grpc.CallOption) (*GetPublicPlaytestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicPlaytestResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetPublicPlaytest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetPublicConfig(ctx context.Context, in *GetPublicConfigRequest, opts ...grpc.CallOption) (*GetPublicConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicConfigResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetPublicConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetPlaytestForPlayer(ctx context.Context, in *GetPlaytestForPlayerRequest, opts ...grpc.CallOption) (*GetPlaytestForPlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaytestForPlayerResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetPlaytestForPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoAmIResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_WhoAmI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) AdminGetPlaytest(ctx context.Context, in *AdminGetPlaytestRequest, opts ...grpc.CallOption) (*AdminGetPlaytestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminGetPlaytestResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_AdminGetPlaytest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) ListPlaytests(ctx context.Context, in *ListPlaytestsRequest, opts ...grpc.CallOption) (*ListPlaytestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlaytestsResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_ListPlaytests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) CreatePlaytest(ctx context.Context, in *CreatePlaytestRequest, opts ...grpc.CallOption) (*CreatePlaytestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlaytestResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_CreatePlaytest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) EditPlaytest(ctx context.Context, in *EditPlaytestRequest, opts ...grpc.CallOption) (*EditPlaytestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditPlaytestResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_EditPlaytest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) SoftDeletePlaytest(ctx context.Context, in *SoftDeletePlaytestRequest, opts ...grpc.CallOption) (*SoftDeletePlaytestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoftDeletePlaytestResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_SoftDeletePlaytest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) TransitionPlaytestStatus(ctx context.Context, in *TransitionPlaytestStatusRequest, opts ...grpc.CallOption) (*TransitionPlaytestStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionPlaytestStatusResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_TransitionPlaytestStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) ExchangeDiscordCode(ctx context.Context, in *ExchangeDiscordCodeRequest, opts ...grpc.CallOption) (*ExchangeDiscordCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeDiscordCodeResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_ExchangeDiscordCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_Signup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetApplicantStatus(ctx context.Context, in *GetApplicantStatusRequest, opts ...grpc.CallOption) (*GetApplicantStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplicantStatusResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetApplicantStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) AcceptNDA(ctx context.Context, in *AcceptNDARequest, opts ...grpc.CallOption) (*AcceptNDAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptNDAResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_AcceptNDA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetGrantedCode(ctx context.Context, in *GetGrantedCodeRequest, opts ...grpc.CallOption) (*GetGrantedCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGrantedCodeResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetGrantedCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetADTDownloadInfo(ctx context.Context, in *GetADTDownloadInfoRequest, opts ...grpc.CallOption) (*GetADTDownloadInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetADTDownloadInfoResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetADTDownloadInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) ListApplicants(ctx context.Context, in *ListApplicantsRequest, opts ...grpc.CallOption) (*ListApplicantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApplicantsResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_ListApplicants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) ApproveApplicant(ctx context.Context, in *ApproveApplicantRequest, opts ...grpc.CallOption) (*ApproveApplicantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveApplicantResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_ApproveApplicant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) RejectApplicant(ctx context.Context, in *RejectApplicantRequest, opts ...grpc.CallOption) (*RejectApplicantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectApplicantResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_RejectApplicant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) RetryDM(ctx context.Context, in *RetryDMRequest, opts ...grpc.CallOption) (*RetryDMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryDMResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_RetryDM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) UploadCodes(ctx context.Context, in *UploadCodesRequest, opts ...grpc.CallOption) (*UploadCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadCodesResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_UploadCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) TopUpCodes(ctx context.Context, in *TopUpCodesRequest, opts ...grpc.CallOption) (*TopUpCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopUpCodesResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_TopUpCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) SyncFromAGS(ctx context.Context, in *SyncFromAGSRequest, opts ...grpc.CallOption) (*SyncFromAGSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncFromAGSResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_SyncFromAGS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetCodePool(ctx context.Context, in *GetCodePoolRequest, opts ...grpc.CallOption) (*GetCodePoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCodePoolResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetCodePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) CreateSurvey(ctx context.Context, in *CreateSurveyRequest, opts ...grpc.CallOption) (*CreateSurveyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSurveyResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_CreateSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) EditSurvey(ctx context.Context, in *EditSurveyRequest, opts ...grpc.CallOption) (*EditSurveyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditSurveyResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_EditSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetSurvey(ctx context.Context, in *GetSurveyRequest, opts ...grpc.CallOption) (*GetSurveyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSurveyResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) SubmitSurveyResponse(ctx context.Context, in *SubmitSurveyResponseRequest, opts ...grpc.CallOption) (*SubmitSurveyResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitSurveyResponseResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_SubmitSurveyResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) ListSurveyResponses(ctx context.Context, in *ListSurveyResponsesRequest, opts ...grpc.CallOption) (*ListSurveyResponsesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSurveyResponsesResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_ListSurveyResponses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) ListAuditLog(ctx context.Context, in *ListAuditLogRequest, opts ...grpc.CallOption) (*ListAuditLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditLogResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_ListAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) RetryFailedDms(ctx context.Context, in *RetryFailedDmsRequest, opts ...grpc.CallOption) (*RetryFailedDmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryFailedDmsResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_RetryFailedDms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetWorkerHealth(ctx context.Context, in *GetWorkerHealthRequest, opts ...grpc.CallOption) (*GetWorkerHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkerHealthResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetWorkerHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) ListADTLinkages(ctx context.Context, in *ListADTLinkagesRequest, opts ...grpc.CallOption) (*ListADTLinkagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListADTLinkagesResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_ListADTLinkages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) StartADTLink(ctx context.Context, in *StartADTLinkRequest, opts ...grpc.CallOption) (*StartADTLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartADTLinkResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_StartADTLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) CompleteADTLink(ctx context.Context, in *CompleteADTLinkRequest, opts ...grpc.CallOption) (*CompleteADTLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteADTLinkResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_CompleteADTLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) UnlinkADT(ctx context.Context, in *UnlinkADTRequest, opts ...grpc.CallOption) (*UnlinkADTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlinkADTResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_UnlinkADT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) RecoverADTLinkage(ctx context.Context, in *RecoverADTLinkageRequest, opts ...grpc.CallOption) (*RecoverADTLinkageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverADTLinkageResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_RecoverADTLinkage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) ListADTBuilds(ctx context.Context, in *ListADTBuildsRequest, opts ...grpc.CallOption) (*ListADTBuildsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListADTBuildsResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_ListADTBuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) ListADTGames(ctx context.Context, in *ListADTGamesRequest, opts ...grpc.CallOption) (*ListADTGamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListADTGamesResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_ListADTGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetADTClientDiagnostics(ctx context.Context, in *GetADTClientDiagnosticsRequest, opts ...grpc.CallOption) (*GetADTClientDiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetADTClientDiagnosticsResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetADTClientDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetPlaytestParticipants(ctx context.Context, in *GetPlaytestParticipantsRequest, opts ...grpc.CallOption) (*GetPlaytestParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaytestParticipantsResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetPlaytestParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) CreateAnnouncement(ctx context.Context, in *CreateAnnouncementRequest, opts ...grpc.CallOption) (*CreateAnnouncementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAnnouncementResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_CreateAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) ListAnnouncements(ctx context.Context, in *ListAnnouncementsRequest, opts ...grpc.CallOption) (*ListAnnouncementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAnnouncementsResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_ListAnnouncements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaytesthubServiceServer is the server API for PlaytesthubService service.
// All implementations should embed UnimplementedPlaytesthubServiceServer
// for forward compatibility.
//
// PlaytesthubService carries every playtesthub RPC. Auth is differentiated
// per-method via OpenAPI Bearer security blocks and permission.action /
// permission.resource options — inspected by the server's auth interceptor
// (pkg/common/authServerInterceptor.go).
//
//   - Unauth    : no Bearer security, no permission.* options.
//   - Player    : Bearer security only. Any authed AGS IAM user.
//   - Admin     : Bearer security + permission.resource + permission.action.
//     MVP authorizes any authed admin session (PRD §9 R8); the
//     permission option still carries the AGS-style resource string
//     so future RBAC can plug in without a proto change.
type PlaytesthubServiceServer interface {
	GetPublicPlaytest(context.Context, *GetPublicPlaytestRequest) (*GetPublicPlaytestResponse, error)
	GetPublicConfig(context.Context, *GetPublicConfigRequest) (*GetPublicConfigResponse, error)
	GetPlaytestForPlayer(context.Context, *GetPlaytestForPlayerRequest) (*GetPlaytestForPlayerResponse, error)
	WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error)
	AdminGetPlaytest(context.Context, *AdminGetPlaytestRequest) (*AdminGetPlaytestResponse, error)
	ListPlaytests(context.Context, *ListPlaytestsRequest) (*ListPlaytestsResponse, error)
	CreatePlaytest(context.Context, *CreatePlaytestRequest) (*CreatePlaytestResponse, error)
	EditPlaytest(context.Context, *EditPlaytestRequest) (*EditPlaytestResponse, error)
	SoftDeletePlaytest(context.Context, *SoftDeletePlaytestRequest) (*SoftDeletePlaytestResponse, error)
	TransitionPlaytestStatus(context.Context, *TransitionPlaytestStatusRequest) (*TransitionPlaytestStatusResponse, error)
	ExchangeDiscordCode(context.Context, *ExchangeDiscordCodeRequest) (*ExchangeDiscordCodeResponse, error)
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	GetApplicantStatus(context.Context, *GetApplicantStatusRequest) (*GetApplicantStatusResponse, error)
	AcceptNDA(context.Context, *AcceptNDARequest) (*AcceptNDAResponse, error)
	GetGrantedCode(context.Context, *GetGrantedCodeRequest) (*GetGrantedCodeResponse, error)
	// GetADTDownloadInfo — ADT-distribution equivalent of GetGrantedCode
	// (PRD §4.8 / M5.B). Player-only; gated on APPROVED applicant row.
	GetADTDownloadInfo(context.Context, *GetADTDownloadInfoRequest) (*GetADTDownloadInfoResponse, error)
	ListApplicants(context.Context, *ListApplicantsRequest) (*ListApplicantsResponse, error)
	ApproveApplicant(context.Context, *ApproveApplicantRequest) (*ApproveApplicantResponse, error)
	RejectApplicant(context.Context, *RejectApplicantRequest) (*RejectApplicantResponse, error)
	RetryDM(context.Context, *RetryDMRequest) (*RetryDMResponse, error)
	UploadCodes(context.Context, *UploadCodesRequest) (*UploadCodesResponse, error)
	TopUpCodes(context.Context, *TopUpCodesRequest) (*TopUpCodesResponse, error)
	SyncFromAGS(context.Context, *SyncFromAGSRequest) (*SyncFromAGSResponse, error)
	GetCodePool(context.Context, *GetCodePoolRequest) (*GetCodePoolResponse, error)
	CreateSurvey(context.Context, *CreateSurveyRequest) (*CreateSurveyResponse, error)
	EditSurvey(context.Context, *EditSurveyRequest) (*EditSurveyResponse, error)
	GetSurvey(context.Context, *GetSurveyRequest) (*GetSurveyResponse, error)
	SubmitSurveyResponse(context.Context, *SubmitSurveyResponseRequest) (*SubmitSurveyResponseResponse, error)
	ListSurveyResponses(context.Context, *ListSurveyResponsesRequest) (*ListSurveyResponsesResponse, error)
	ListAuditLog(context.Context, *ListAuditLogRequest) (*ListAuditLogResponse, error)
	RetryFailedDms(context.Context, *RetryFailedDmsRequest) (*RetryFailedDmsResponse, error)
	GetWorkerHealth(context.Context, *GetWorkerHealthRequest) (*GetWorkerHealthResponse, error)
	ListADTLinkages(context.Context, *ListADTLinkagesRequest) (*ListADTLinkagesResponse, error)
	StartADTLink(context.Context, *StartADTLinkRequest) (*StartADTLinkResponse, error)
	CompleteADTLink(context.Context, *CompleteADTLinkRequest) (*CompleteADTLinkResponse, error)
	UnlinkADT(context.Context, *UnlinkADTRequest) (*UnlinkADTResponse, error)
	RecoverADTLinkage(context.Context, *RecoverADTLinkageRequest) (*RecoverADTLinkageResponse, error)
	ListADTBuilds(context.Context, *ListADTBuildsRequest) (*ListADTBuildsResponse, error)
	ListADTGames(context.Context, *ListADTGamesRequest) (*ListADTGamesResponse, error)
	GetADTClientDiagnostics(context.Context, *GetADTClientDiagnosticsRequest) (*GetADTClientDiagnosticsResponse, error)
	// M5.C — participants surface backing the detail page Participants tab.
	// Cache-only read; the four ADT telemetry cache columns ship dormant in
	// M5.C (NULL/zero across the milestone — M6 lights them up).
	GetPlaytestParticipants(context.Context, *GetPlaytestParticipantsRequest) (*GetPlaytestParticipantsResponse, error)
	// M5.C — bulk announcement broadcast (PRD §5.4 "Bulk announcements").
	// Resolves the recipient set at call time; fans out via the existing
	// M2 RetryDM machinery.
	CreateAnnouncement(context.Context, *CreateAnnouncementRequest) (*CreateAnnouncementResponse, error)
	ListAnnouncements(context.Context, *ListAnnouncementsRequest) (*ListAnnouncementsResponse, error)
}

// UnimplementedPlaytesthubServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlaytesthubServiceServer struct{}

func (UnimplementedPlaytesthubServiceServer) GetPublicPlaytest(context.Context, *GetPublicPlaytestRequest) (*GetPublicPlaytestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicPlaytest not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetPublicConfig(context.Context, *GetPublicConfigRequest) (*GetPublicConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicConfig not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetPlaytestForPlayer(context.Context, *GetPlaytestForPlayerRequest) (*GetPlaytestForPlayerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlaytestForPlayer not implemented")
}
func (UnimplementedPlaytesthubServiceServer) WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WhoAmI not implemented")
}
func (UnimplementedPlaytesthubServiceServer) AdminGetPlaytest(context.Context, *AdminGetPlaytestRequest) (*AdminGetPlaytestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminGetPlaytest not implemented")
}
func (UnimplementedPlaytesthubServiceServer) ListPlaytests(context.Context, *ListPlaytestsRequest) (*ListPlaytestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlaytests not implemented")
}
func (UnimplementedPlaytesthubServiceServer) CreatePlaytest(context.Context, *CreatePlaytestRequest) (*CreatePlaytestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlaytest not implemented")
}
func (UnimplementedPlaytesthubServiceServer) EditPlaytest(context.Context, *EditPlaytestRequest) (*EditPlaytestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditPlaytest not implemented")
}
func (UnimplementedPlaytesthubServiceServer) SoftDeletePlaytest(context.Context, *SoftDeletePlaytestRequest) (*SoftDeletePlaytestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SoftDeletePlaytest not implemented")
}
func (UnimplementedPlaytesthubServiceServer) TransitionPlaytestStatus(context.Context, *TransitionPlaytestStatusRequest) (*TransitionPlaytestStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransitionPlaytestStatus not implemented")
}
func (UnimplementedPlaytesthubServiceServer) ExchangeDiscordCode(context.Context, *ExchangeDiscordCodeRequest) (*ExchangeDiscordCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeDiscordCode not implemented")
}
func (UnimplementedPlaytesthubServiceServer) Signup(context.Context, *SignupRequest) (*SignupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetApplicantStatus(context.Context, *GetApplicantStatusRequest) (*GetApplicantStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicantStatus not implemented")
}
func (UnimplementedPlaytesthubServiceServer) AcceptNDA(context.Context, *AcceptNDARequest) (*AcceptNDAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptNDA not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetGrantedCode(context.Context, *GetGrantedCodeRequest) (*GetGrantedCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGrantedCode not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetADTDownloadInfo(context.Context, *GetADTDownloadInfoRequest) (*GetADTDownloadInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetADTDownloadInfo not implemented")
}
func (UnimplementedPlaytesthubServiceServer) ListApplicants(context.Context, *ListApplicantsRequest) (*ListApplicantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplicants not implemented")
}
func (UnimplementedPlaytesthubServiceServer) ApproveApplicant(context.Context, *ApproveApplicantRequest) (*ApproveApplicantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveApplicant not implemented")
}
func (UnimplementedPlaytesthubServiceServer) RejectApplicant(context.Context, *RejectApplicantRequest) (*RejectApplicantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectApplicant not implemented")
}
func (UnimplementedPlaytesthubServiceServer) RetryDM(context.Context, *RetryDMRequest) (*RetryDMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryDM not implemented")
}
func (UnimplementedPlaytesthubServiceServer) UploadCodes(context.Context, *UploadCodesRequest) (*UploadCodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadCodes not implemented")
}
func (UnimplementedPlaytesthubServiceServer) TopUpCodes(context.Context, *TopUpCodesRequest) (*TopUpCodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TopUpCodes not implemented")
}
func (UnimplementedPlaytesthubServiceServer) SyncFromAGS(context.Context, *SyncFromAGSRequest) (*SyncFromAGSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncFromAGS not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetCodePool(context.Context, *GetCodePoolRequest) (*GetCodePoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCodePool not implemented")
}
func (UnimplementedPlaytesthubServiceServer) CreateSurvey(context.Context, *CreateSurveyRequest) (*CreateSurveyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSurvey not implemented")
}
func (UnimplementedPlaytesthubServiceServer) EditSurvey(context.Context, *EditSurveyRequest) (*EditSurveyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditSurvey not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetSurvey(context.Context, *GetSurveyRequest) (*GetSurveyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSurvey not implemented")
}
func (UnimplementedPlaytesthubServiceServer) SubmitSurveyResponse(context.Context, *SubmitSurveyResponseRequest) (*SubmitSurveyResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSurveyResponse not implemented")
}
func (UnimplementedPlaytesthubServiceServer) ListSurveyResponses(context.Context, *ListSurveyResponsesRequest) (*ListSurveyResponsesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSurveyResponses not implemented")
}
func (UnimplementedPlaytesthubServiceServer) ListAuditLog(context.Context, *ListAuditLogRequest) (*ListAuditLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditLog not implemented")
}
func (UnimplementedPlaytesthubServiceServer) RetryFailedDms(context.Context, *RetryFailedDmsRequest) (*RetryFailedDmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryFailedDms not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetWorkerHealth(context.Context, *GetWorkerHealthRequest) (*GetWorkerHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkerHealth not implemented")
}
func (UnimplementedPlaytesthubServiceServer) ListADTLinkages(context.Context, *ListADTLinkagesRequest) (*ListADTLinkagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListADTLinkages not implemented")
}
func (UnimplementedPlaytesthubServiceServer) StartADTLink(context.Context, *StartADTLinkRequest) (*StartADTLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartADTLink not implemented")
}
func (UnimplementedPlaytesthubServiceServer) CompleteADTLink(context.Context, *CompleteADTLinkRequest) (*CompleteADTLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteADTLink not implemented")
}
func (UnimplementedPlaytesthubServiceServer) UnlinkADT(context.Context, *UnlinkADTRequest) (*UnlinkADTResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlinkADT not implemented")
}
func (UnimplementedPlaytesthubServiceServer) RecoverADTLinkage(context.Context, *RecoverADTLinkageRequest) (*RecoverADTLinkageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoverADTLinkage not implemented")
}
func (UnimplementedPlaytesthubServiceServer) ListADTBuilds(context.Context, *ListADTBuildsRequest) (*ListADTBuildsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListADTBuilds not implemented")
}
func (UnimplementedPlaytesthubServiceServer) ListADTGames(context.Context, *ListADTGamesRequest) (*ListADTGamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListADTGames not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetADTClientDiagnostics(context.Context, *GetADTClientDiagnosticsRequest) (*GetADTClientDiagnosticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetADTClientDiagnostics not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetPlaytestParticipants(context.Context, *GetPlaytestParticipantsRequest) (*GetPlaytestParticipantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlaytestParticipants not implemented")
}
func (UnimplementedPlaytesthubServiceServer) CreateAnnouncement(context.Context, *CreateAnnouncementRequest) (*CreateAnnouncementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAnnouncement not implemented")
}
func (UnimplementedPlaytesthubServiceServer) ListAnnouncements(context.Context, *ListAnnouncementsRequest) (*ListAnnouncementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAnnouncements not implemented")
}
func (UnimplementedPlaytesthubServiceServer) testEmbeddedByValue() {}

// UnsafePlaytesthubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaytesthubServiceServer will
// result in compilation errors.
type UnsafePlaytesthubServiceServer interface {
	mustEmbedUnimplementedPlaytesthubServiceServer()
}

func RegisterPlaytesthubServiceServer(s grpc.ServiceRegistrar, srv PlaytesthubServiceServer) {
	// If the following call panics, it indicates UnimplementedPlaytesthubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlaytesthubService_ServiceDesc, srv)
}

func _PlaytesthubService_GetPublicPlaytest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicPlaytestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetPublicPlaytest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetPublicPlaytest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetPublicPlaytest(ctx, req.(*GetPublicPlaytestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetPublicConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetPublicConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetPublicConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetPublicConfig(ctx, req.(*GetPublicConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetPlaytestForPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaytestForPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetPlaytestForPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetPlaytestForPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetPlaytestForPlayer(ctx, req.(*GetPlaytestForPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_WhoAmI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).WhoAmI(ctx, req.(*WhoAmIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_AdminGetPlaytest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminGetPlaytestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).AdminGetPlaytest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_AdminGetPlaytest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).AdminGetPlaytest(ctx, req.(*AdminGetPlaytestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_ListPlaytests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlaytestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).ListPlaytests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_ListPlaytests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).ListPlaytests(ctx, req.(*ListPlaytestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_CreatePlaytest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlaytestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).CreatePlaytest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_CreatePlaytest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).CreatePlaytest(ctx, req.(*CreatePlaytestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_EditPlaytest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditPlaytestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).EditPlaytest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_EditPlaytest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).EditPlaytest(ctx, req.(*EditPlaytestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_SoftDeletePlaytest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SoftDeletePlaytestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).SoftDeletePlaytest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_SoftDeletePlaytest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).SoftDeletePlaytest(ctx, req.(*SoftDeletePlaytestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_TransitionPlaytestStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionPlaytestStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).TransitionPlaytestStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_TransitionPlaytestStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).TransitionPlaytestStatus(ctx, req.(*TransitionPlaytestStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_ExchangeDiscordCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeDiscordCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).ExchangeDiscordCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_ExchangeDiscordCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).ExchangeDiscordCode(ctx, req.(*ExchangeDiscordCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_Signup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetApplicantStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicantStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetApplicantStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetApplicantStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetApplicantStatus(ctx, req.(*GetApplicantStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_AcceptNDA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptNDARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).AcceptNDA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_AcceptNDA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).AcceptNDA(ctx, req.(*AcceptNDARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetGrantedCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGrantedCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetGrantedCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetGrantedCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetGrantedCode(ctx, req.(*GetGrantedCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetADTDownloadInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetADTDownloadInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetADTDownloadInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetADTDownloadInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetADTDownloadInfo(ctx, req.(*GetADTDownloadInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_ListApplicants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).ListApplicants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_ListApplicants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).ListApplicants(ctx, req.(*ListApplicantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_ApproveApplicant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveApplicantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).ApproveApplicant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_ApproveApplicant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).ApproveApplicant(ctx, req.(*ApproveApplicantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_RejectApplicant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectApplicantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).RejectApplicant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_RejectApplicant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).RejectApplicant(ctx, req.(*RejectApplicantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_RetryDM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryDMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).RetryDM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_RetryDM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).RetryDM(ctx, req.(*RetryDMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_UploadCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).UploadCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_UploadCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).UploadCodes(ctx, req.(*UploadCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_TopUpCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopUpCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).TopUpCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_TopUpCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).TopUpCodes(ctx, req.(*TopUpCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_SyncFromAGS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncFromAGSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).SyncFromAGS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_SyncFromAGS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).SyncFromAGS(ctx, req.(*SyncFromAGSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetCodePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCodePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetCodePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetCodePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetCodePool(ctx, req.(*GetCodePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_CreateSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).CreateSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_CreateSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).CreateSurvey(ctx, req.(*CreateSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_EditSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).EditSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_EditSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).EditSurvey(ctx, req.(*EditSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetSurvey(ctx, req.(*GetSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_SubmitSurveyResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitSurveyResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).SubmitSurveyResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_SubmitSurveyResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).SubmitSurveyResponse(ctx, req.(*SubmitSurveyResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_ListSurveyResponses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSurveyResponsesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).ListSurveyResponses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_ListSurveyResponses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).ListSurveyResponses(ctx, req.(*ListSurveyResponsesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_ListAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).ListAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_ListAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).ListAuditLog(ctx, req.(*ListAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_RetryFailedDms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryFailedDmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).RetryFailedDms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_RetryFailedDms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).RetryFailedDms(ctx, req.(*RetryFailedDmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetWorkerHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkerHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetWorkerHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetWorkerHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetWorkerHealth(ctx, req.(*GetWorkerHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_ListADTLinkages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListADTLinkagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).ListADTLinkages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_ListADTLinkages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).ListADTLinkages(ctx, req.(*ListADTLinkagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_StartADTLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartADTLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).StartADTLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_StartADTLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).StartADTLink(ctx, req.(*StartADTLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_CompleteADTLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteADTLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).CompleteADTLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_CompleteADTLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).CompleteADTLink(ctx, req.(*CompleteADTLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_UnlinkADT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkADTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).UnlinkADT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_UnlinkADT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).UnlinkADT(ctx, req.(*UnlinkADTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_RecoverADTLinkage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverADTLinkageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).RecoverADTLinkage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_RecoverADTLinkage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).RecoverADTLinkage(ctx, req.(*RecoverADTLinkageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_ListADTBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListADTBuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).ListADTBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_ListADTBuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).ListADTBuilds(ctx, req.(*ListADTBuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_ListADTGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListADTGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).ListADTGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_ListADTGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).ListADTGames(ctx, req.(*ListADTGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetADTClientDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetADTClientDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetADTClientDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetADTClientDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetADTClientDiagnostics(ctx, req.(*GetADTClientDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetPlaytestParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaytestParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetPlaytestParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetPlaytestParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetPlaytestParticipants(ctx, req.(*GetPlaytestParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_CreateAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).CreateAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_CreateAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).CreateAnnouncement(ctx, req.(*CreateAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_ListAnnouncements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAnnouncementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).ListAnnouncements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_ListAnnouncements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).ListAnnouncements(ctx, req.(*ListAnnouncementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlaytesthubService_ServiceDesc is the grpc.ServiceDesc for PlaytesthubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlaytesthubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "playtesthub.v1.PlaytesthubService",
	HandlerType: (*PlaytesthubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicPlaytest",
			Handler:    _PlaytesthubService_GetPublicPlaytest_Handler,
		},
		{
			MethodName: "GetPublicConfig",
			Handler:    _PlaytesthubService_GetPublicConfig_Handler,
		},
		{
			MethodName: "GetPlaytestForPlayer",
			Handler:    _PlaytesthubService_GetPlaytestForPlayer_Handler,
		},
		{
			MethodName: "WhoAmI",
			Handler:    _PlaytesthubService_WhoAmI_Handler,
		},
		{
			MethodName: "AdminGetPlaytest",
			Handler:    _PlaytesthubService_AdminGetPlaytest_Handler,
		},
		{
			MethodName: "ListPlaytests",
			Handler:    _PlaytesthubService_ListPlaytests_Handler,
		},
		{
			MethodName: "CreatePlaytest",
			Handler:    _PlaytesthubService_CreatePlaytest_Handler,
		},
		{
			MethodName: "EditPlaytest",
			Handler:    _PlaytesthubService_EditPlaytest_Handler,
		},
		{
			MethodName: "SoftDeletePlaytest",
			Handler:    _PlaytesthubService_SoftDeletePlaytest_Handler,
		},
		{
			MethodName: "TransitionPlaytestStatus",
			Handler:    _PlaytesthubService_TransitionPlaytestStatus_Handler,
		},
		{
			MethodName: "ExchangeDiscordCode",
			Handler:    _PlaytesthubService_ExchangeDiscordCode_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _PlaytesthubService_Signup_Handler,
		},
		{
			MethodName: "GetApplicantStatus",
			Handler:    _PlaytesthubService_GetApplicantStatus_Handler,
		},
		{
			MethodName: "AcceptNDA",
			Handler:    _PlaytesthubService_AcceptNDA_Handler,
		},
		{
			MethodName: "GetGrantedCode",
			Handler:    _PlaytesthubService_GetGrantedCode_Handler,
		},
		{
			MethodName: "GetADTDownloadInfo",
			Handler:    _PlaytesthubService_GetADTDownloadInfo_Handler,
		},
		{
			MethodName: "ListApplicants",
			Handler:    _PlaytesthubService_ListApplicants_Handler,
		},
		{
			MethodName: "ApproveApplicant",
			Handler:    _PlaytesthubService_ApproveApplicant_Handler,
		},
		{
			MethodName: "RejectApplicant",
			Handler:    _PlaytesthubService_RejectApplicant_Handler,
		},
		{
			MethodName: "RetryDM",
			Handler:    _PlaytesthubService_RetryDM_Handler,
		},
		{
			MethodName: "UploadCodes",
			Handler:    _PlaytesthubService_UploadCodes_Handler,
		},
		{
			MethodName: "TopUpCodes",
			Handler:    _PlaytesthubService_TopUpCodes_Handler,
		},
		{
			MethodName: "SyncFromAGS",
			Handler:    _PlaytesthubService_SyncFromAGS_Handler,
		},
		{
			MethodName: "GetCodePool",
			Handler:    _PlaytesthubService_GetCodePool_Handler,
		},
		{
			MethodName: "CreateSurvey",
			Handler:    _PlaytesthubService_CreateSurvey_Handler,
		},
		{
			MethodName: "EditSurvey",
			Handler:    _PlaytesthubService_EditSurvey_Handler,
		},
		{
			MethodName: "GetSurvey",
			Handler:    _PlaytesthubService_GetSurvey_Handler,
		},
		{
			MethodName: "SubmitSurveyResponse",
			Handler:    _PlaytesthubService_SubmitSurveyResponse_Handler,
		},
		{
			MethodName: "ListSurveyResponses",
			Handler:    _PlaytesthubService_ListSurveyResponses_Handler,
		},
		{
			MethodName: "ListAuditLog",
			Handler:    _PlaytesthubService_ListAuditLog_Handler,
		},
		{
			MethodName: "RetryFailedDms",
			Handler:    _PlaytesthubService_RetryFailedDms_Handler,
		},
		{
			MethodName: "GetWorkerHealth",
			Handler:    _PlaytesthubService_GetWorkerHealth_Handler,
		},
		{
			MethodName: "ListADTLinkages",
			Handler:    _PlaytesthubService_ListADTLinkages_Handler,
		},
		{
			MethodName: "StartADTLink",
			Handler:    _PlaytesthubService_StartADTLink_Handler,
		},
		{
			MethodName: "CompleteADTLink",
			Handler:    _PlaytesthubService_CompleteADTLink_Handler,
		},
		{
			MethodName: "UnlinkADT",
			Handler:    _PlaytesthubService_UnlinkADT_Handler,
		},
		{
			MethodName: "RecoverADTLinkage",
			Handler:    _PlaytesthubService_RecoverADTLinkage_Handler,
		},
		{
			MethodName: "ListADTBuilds",
			Handler:    _PlaytesthubService_ListADTBuilds_Handler,
		},
		{
			MethodName: "ListADTGames",
			Handler:    _PlaytesthubService_ListADTGames_Handler,
		},
		{
			MethodName: "GetADTClientDiagnostics",
			Handler:    _PlaytesthubService_GetADTClientDiagnostics_Handler,
		},
		{
			MethodName: "GetPlaytestParticipants",
			Handler:    _PlaytesthubService_GetPlaytestParticipants_Handler,
		},
		{
			MethodName: "CreateAnnouncement",
			Handler:    _PlaytesthubService_CreateAnnouncement_Handler,
		},
		{
			MethodName: "ListAnnouncements",
			Handler:    _PlaytesthubService_ListAnnouncements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "playtesthub/v1/playtesthub.proto",
}
