// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: playtesthub/v1/playtesthub.proto

package playtesthubv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlaytesthubService_GetPublicPlaytest_FullMethodName        = "/playtesthub.v1.PlaytesthubService/GetPublicPlaytest"
	PlaytesthubService_GetPlaytestForPlayer_FullMethodName     = "/playtesthub.v1.PlaytesthubService/GetPlaytestForPlayer"
	PlaytesthubService_AdminGetPlaytest_FullMethodName         = "/playtesthub.v1.PlaytesthubService/AdminGetPlaytest"
	PlaytesthubService_ListPlaytests_FullMethodName            = "/playtesthub.v1.PlaytesthubService/ListPlaytests"
	PlaytesthubService_CreatePlaytest_FullMethodName           = "/playtesthub.v1.PlaytesthubService/CreatePlaytest"
	PlaytesthubService_EditPlaytest_FullMethodName             = "/playtesthub.v1.PlaytesthubService/EditPlaytest"
	PlaytesthubService_SoftDeletePlaytest_FullMethodName       = "/playtesthub.v1.PlaytesthubService/SoftDeletePlaytest"
	PlaytesthubService_TransitionPlaytestStatus_FullMethodName = "/playtesthub.v1.PlaytesthubService/TransitionPlaytestStatus"
	PlaytesthubService_GetDiscordLoginUrl_FullMethodName       = "/playtesthub.v1.PlaytesthubService/GetDiscordLoginUrl"
	PlaytesthubService_Signup_FullMethodName                   = "/playtesthub.v1.PlaytesthubService/Signup"
	PlaytesthubService_GetApplicantStatus_FullMethodName       = "/playtesthub.v1.PlaytesthubService/GetApplicantStatus"
)

// PlaytesthubServiceClient is the client API for PlaytesthubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlaytesthubService carries every playtesthub RPC. Auth is differentiated
// per-method via OpenAPI Bearer security blocks and permission.action /
// permission.resource options — inspected by the server's auth interceptor
// (pkg/common/authServerInterceptor.go).
//
//   - Unauth    : no Bearer security, no permission.* options.
//   - Player    : Bearer security only. Any authed AGS IAM user.
//   - Admin     : Bearer security + permission.resource + permission.action.
//     MVP authorizes any authed admin session (PRD §9 R8); the
//     permission option still carries the AGS-style resource string
//     so future RBAC can plug in without a proto change.
type PlaytesthubServiceClient interface {
	GetPublicPlaytest(ctx context.Context, in *GetPublicPlaytestRequest, opts ...grpc.CallOption) (*GetPublicPlaytestResponse, error)
	GetPlaytestForPlayer(ctx context.Context, in *GetPlaytestForPlayerRequest, opts ...grpc.CallOption) (*GetPlaytestForPlayerResponse, error)
	AdminGetPlaytest(ctx context.Context, in *AdminGetPlaytestRequest, opts ...grpc.CallOption) (*AdminGetPlaytestResponse, error)
	ListPlaytests(ctx context.Context, in *ListPlaytestsRequest, opts ...grpc.CallOption) (*ListPlaytestsResponse, error)
	CreatePlaytest(ctx context.Context, in *CreatePlaytestRequest, opts ...grpc.CallOption) (*CreatePlaytestResponse, error)
	EditPlaytest(ctx context.Context, in *EditPlaytestRequest, opts ...grpc.CallOption) (*EditPlaytestResponse, error)
	SoftDeletePlaytest(ctx context.Context, in *SoftDeletePlaytestRequest, opts ...grpc.CallOption) (*SoftDeletePlaytestResponse, error)
	TransitionPlaytestStatus(ctx context.Context, in *TransitionPlaytestStatusRequest, opts ...grpc.CallOption) (*TransitionPlaytestStatusResponse, error)
	GetDiscordLoginUrl(ctx context.Context, in *GetDiscordLoginUrlRequest, opts ...grpc.CallOption) (*GetDiscordLoginUrlResponse, error)
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	GetApplicantStatus(ctx context.Context, in *GetApplicantStatusRequest, opts ...grpc.CallOption) (*GetApplicantStatusResponse, error)
}

type playtesthubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaytesthubServiceClient(cc grpc.ClientConnInterface) PlaytesthubServiceClient {
	return &playtesthubServiceClient{cc}
}

func (c *playtesthubServiceClient) GetPublicPlaytest(ctx context.Context, in *GetPublicPlaytestRequest, opts ...grpc.CallOption) (*GetPublicPlaytestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicPlaytestResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetPublicPlaytest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetPlaytestForPlayer(ctx context.Context, in *GetPlaytestForPlayerRequest, opts ...grpc.CallOption) (*GetPlaytestForPlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaytestForPlayerResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetPlaytestForPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) AdminGetPlaytest(ctx context.Context, in *AdminGetPlaytestRequest, opts ...grpc.CallOption) (*AdminGetPlaytestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminGetPlaytestResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_AdminGetPlaytest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) ListPlaytests(ctx context.Context, in *ListPlaytestsRequest, opts ...grpc.CallOption) (*ListPlaytestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlaytestsResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_ListPlaytests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) CreatePlaytest(ctx context.Context, in *CreatePlaytestRequest, opts ...grpc.CallOption) (*CreatePlaytestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlaytestResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_CreatePlaytest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) EditPlaytest(ctx context.Context, in *EditPlaytestRequest, opts ...grpc.CallOption) (*EditPlaytestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditPlaytestResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_EditPlaytest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) SoftDeletePlaytest(ctx context.Context, in *SoftDeletePlaytestRequest, opts ...grpc.CallOption) (*SoftDeletePlaytestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoftDeletePlaytestResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_SoftDeletePlaytest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) TransitionPlaytestStatus(ctx context.Context, in *TransitionPlaytestStatusRequest, opts ...grpc.CallOption) (*TransitionPlaytestStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionPlaytestStatusResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_TransitionPlaytestStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetDiscordLoginUrl(ctx context.Context, in *GetDiscordLoginUrlRequest, opts ...grpc.CallOption) (*GetDiscordLoginUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiscordLoginUrlResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetDiscordLoginUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_Signup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playtesthubServiceClient) GetApplicantStatus(ctx context.Context, in *GetApplicantStatusRequest, opts ...grpc.CallOption) (*GetApplicantStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplicantStatusResponse)
	err := c.cc.Invoke(ctx, PlaytesthubService_GetApplicantStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaytesthubServiceServer is the server API for PlaytesthubService service.
// All implementations should embed UnimplementedPlaytesthubServiceServer
// for forward compatibility.
//
// PlaytesthubService carries every playtesthub RPC. Auth is differentiated
// per-method via OpenAPI Bearer security blocks and permission.action /
// permission.resource options — inspected by the server's auth interceptor
// (pkg/common/authServerInterceptor.go).
//
//   - Unauth    : no Bearer security, no permission.* options.
//   - Player    : Bearer security only. Any authed AGS IAM user.
//   - Admin     : Bearer security + permission.resource + permission.action.
//     MVP authorizes any authed admin session (PRD §9 R8); the
//     permission option still carries the AGS-style resource string
//     so future RBAC can plug in without a proto change.
type PlaytesthubServiceServer interface {
	GetPublicPlaytest(context.Context, *GetPublicPlaytestRequest) (*GetPublicPlaytestResponse, error)
	GetPlaytestForPlayer(context.Context, *GetPlaytestForPlayerRequest) (*GetPlaytestForPlayerResponse, error)
	AdminGetPlaytest(context.Context, *AdminGetPlaytestRequest) (*AdminGetPlaytestResponse, error)
	ListPlaytests(context.Context, *ListPlaytestsRequest) (*ListPlaytestsResponse, error)
	CreatePlaytest(context.Context, *CreatePlaytestRequest) (*CreatePlaytestResponse, error)
	EditPlaytest(context.Context, *EditPlaytestRequest) (*EditPlaytestResponse, error)
	SoftDeletePlaytest(context.Context, *SoftDeletePlaytestRequest) (*SoftDeletePlaytestResponse, error)
	TransitionPlaytestStatus(context.Context, *TransitionPlaytestStatusRequest) (*TransitionPlaytestStatusResponse, error)
	GetDiscordLoginUrl(context.Context, *GetDiscordLoginUrlRequest) (*GetDiscordLoginUrlResponse, error)
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	GetApplicantStatus(context.Context, *GetApplicantStatusRequest) (*GetApplicantStatusResponse, error)
}

// UnimplementedPlaytesthubServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlaytesthubServiceServer struct{}

func (UnimplementedPlaytesthubServiceServer) GetPublicPlaytest(context.Context, *GetPublicPlaytestRequest) (*GetPublicPlaytestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicPlaytest not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetPlaytestForPlayer(context.Context, *GetPlaytestForPlayerRequest) (*GetPlaytestForPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaytestForPlayer not implemented")
}
func (UnimplementedPlaytesthubServiceServer) AdminGetPlaytest(context.Context, *AdminGetPlaytestRequest) (*AdminGetPlaytestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminGetPlaytest not implemented")
}
func (UnimplementedPlaytesthubServiceServer) ListPlaytests(context.Context, *ListPlaytestsRequest) (*ListPlaytestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlaytests not implemented")
}
func (UnimplementedPlaytesthubServiceServer) CreatePlaytest(context.Context, *CreatePlaytestRequest) (*CreatePlaytestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlaytest not implemented")
}
func (UnimplementedPlaytesthubServiceServer) EditPlaytest(context.Context, *EditPlaytestRequest) (*EditPlaytestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditPlaytest not implemented")
}
func (UnimplementedPlaytesthubServiceServer) SoftDeletePlaytest(context.Context, *SoftDeletePlaytestRequest) (*SoftDeletePlaytestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SoftDeletePlaytest not implemented")
}
func (UnimplementedPlaytesthubServiceServer) TransitionPlaytestStatus(context.Context, *TransitionPlaytestStatusRequest) (*TransitionPlaytestStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionPlaytestStatus not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetDiscordLoginUrl(context.Context, *GetDiscordLoginUrlRequest) (*GetDiscordLoginUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiscordLoginUrl not implemented")
}
func (UnimplementedPlaytesthubServiceServer) Signup(context.Context, *SignupRequest) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedPlaytesthubServiceServer) GetApplicantStatus(context.Context, *GetApplicantStatusRequest) (*GetApplicantStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicantStatus not implemented")
}
func (UnimplementedPlaytesthubServiceServer) testEmbeddedByValue() {}

// UnsafePlaytesthubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaytesthubServiceServer will
// result in compilation errors.
type UnsafePlaytesthubServiceServer interface {
	mustEmbedUnimplementedPlaytesthubServiceServer()
}

func RegisterPlaytesthubServiceServer(s grpc.ServiceRegistrar, srv PlaytesthubServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlaytesthubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlaytesthubService_ServiceDesc, srv)
}

func _PlaytesthubService_GetPublicPlaytest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicPlaytestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetPublicPlaytest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetPublicPlaytest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetPublicPlaytest(ctx, req.(*GetPublicPlaytestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetPlaytestForPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaytestForPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetPlaytestForPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetPlaytestForPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetPlaytestForPlayer(ctx, req.(*GetPlaytestForPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_AdminGetPlaytest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminGetPlaytestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).AdminGetPlaytest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_AdminGetPlaytest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).AdminGetPlaytest(ctx, req.(*AdminGetPlaytestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_ListPlaytests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlaytestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).ListPlaytests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_ListPlaytests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).ListPlaytests(ctx, req.(*ListPlaytestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_CreatePlaytest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlaytestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).CreatePlaytest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_CreatePlaytest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).CreatePlaytest(ctx, req.(*CreatePlaytestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_EditPlaytest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditPlaytestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).EditPlaytest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_EditPlaytest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).EditPlaytest(ctx, req.(*EditPlaytestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_SoftDeletePlaytest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SoftDeletePlaytestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).SoftDeletePlaytest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_SoftDeletePlaytest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).SoftDeletePlaytest(ctx, req.(*SoftDeletePlaytestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_TransitionPlaytestStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionPlaytestStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).TransitionPlaytestStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_TransitionPlaytestStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).TransitionPlaytestStatus(ctx, req.(*TransitionPlaytestStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetDiscordLoginUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscordLoginUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetDiscordLoginUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetDiscordLoginUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetDiscordLoginUrl(ctx, req.(*GetDiscordLoginUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_Signup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaytesthubService_GetApplicantStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicantStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaytesthubServiceServer).GetApplicantStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaytesthubService_GetApplicantStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaytesthubServiceServer).GetApplicantStatus(ctx, req.(*GetApplicantStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlaytesthubService_ServiceDesc is the grpc.ServiceDesc for PlaytesthubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlaytesthubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "playtesthub.v1.PlaytesthubService",
	HandlerType: (*PlaytesthubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicPlaytest",
			Handler:    _PlaytesthubService_GetPublicPlaytest_Handler,
		},
		{
			MethodName: "GetPlaytestForPlayer",
			Handler:    _PlaytesthubService_GetPlaytestForPlayer_Handler,
		},
		{
			MethodName: "AdminGetPlaytest",
			Handler:    _PlaytesthubService_AdminGetPlaytest_Handler,
		},
		{
			MethodName: "ListPlaytests",
			Handler:    _PlaytesthubService_ListPlaytests_Handler,
		},
		{
			MethodName: "CreatePlaytest",
			Handler:    _PlaytesthubService_CreatePlaytest_Handler,
		},
		{
			MethodName: "EditPlaytest",
			Handler:    _PlaytesthubService_EditPlaytest_Handler,
		},
		{
			MethodName: "SoftDeletePlaytest",
			Handler:    _PlaytesthubService_SoftDeletePlaytest_Handler,
		},
		{
			MethodName: "TransitionPlaytestStatus",
			Handler:    _PlaytesthubService_TransitionPlaytestStatus_Handler,
		},
		{
			MethodName: "GetDiscordLoginUrl",
			Handler:    _PlaytesthubService_GetDiscordLoginUrl_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _PlaytesthubService_Signup_Handler,
		},
		{
			MethodName: "GetApplicantStatus",
			Handler:    _PlaytesthubService_GetApplicantStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "playtesthub/v1/playtesthub.proto",
}
